Repository vircadia/vircadia-native-core, pull requests merged in 2019-12, with the labels that each got.

#2 ignores "VideoDecodeStats" in .gitignore
  .gitignore
Labels: enhancement

#3 Upgrade kcpkg port files from SDL2 from 2.0.8 to 2.0.10. This fixes patch issues.
  .gitignore
  cmake/ports/sdl2/CONTROL
  cmake/ports/sdl2/SDL-2.0.9-bug-4391-fix.patch
  cmake/ports/sdl2/disable-hidapi-for-uwp.patch
  cmake/ports/sdl2/enable-winrt-cmake.patch
  cmake/ports/sdl2/fix-arm64-headers.patch
  cmake/ports/sdl2/fix-space-in-path.patch
  cmake/ports/sdl2/fix-x86-windows.patch
  cmake/ports/sdl2/portfile.cmake
  cmake/ports/sdl2/vcpkg-cmake-wrapper.cmake
Labels: bug

#1 Whitelist added to interface.json, accessed by QML and C++
  README.md
  interface/resources/qml/hifi/dialogs/security/EntityScriptWhitelist.qml
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/script-engine/src/ScriptEngine.cpp
Labels: enhancement

#5 scriptengine pulls from inferface.json correctly, removed extra debug…
  interface/resources/qml/hifi/dialogs/security/EntityScriptWhitelist.qml
  libraries/script-engine/src/ScriptEngine.cpp
Labels: bug, enhancement

#6 Fixes Entity Script Whitelist
  libraries/script-engine/src/ScriptEngine.cpp
Labels: bug

#7 Added a confirmation message + instructions to the QML.
  interface/resources/qml/hifi/dialogs/security/EntityScriptWhitelist.qml
Labels: enhancement

#9 Feature/quality of life k2
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
  interface/src/Application.cpp
Labels: enhancement

#11 Replace the interface icons with Kasen logo icon.
  interface/icon/interface-beta.icns
  interface/icon/interface-beta.ico
  interface/icon/interface.icns
  interface/icon/interface.ico
Labels: branding

#10 Removes the environment variable requirement for procedural material shaders
  libraries/render-utils/src/MeshPartPayload.cpp
Labels: enhancement

#12 Adds community script directory, adds chat as default app.
  scripts/community/chat.js
  scripts/defaultScripts.js
Labels: enhancement

#20 Update SDL2 CONTROL file to fix linux build
  cmake/ports/sdl2/CONTROL
Labels: bug

#21 Fix the fix for SDL2
  cmake/ports/sdl2/CONTROL
Labels: bug

#19 Change asset URLs to Athena S3 bucket.
  CMakeLists.txt
  cmake/externals/GifCreator/CMakeLists.txt
  cmake/externals/LibOVR/CMakeLists.txt
  cmake/externals/LibOVRPlatform/CMakeLists.txt
  cmake/externals/crashpad/CMakeLists.txt
  cmake/externals/glad32es/CMakeLists.txt
  cmake/externals/glad41/CMakeLists.txt
  cmake/externals/glad45/CMakeLists.txt
  cmake/externals/hifiAudioCodec/CMakeLists.txt
  cmake/externals/neuron/CMakeLists.txt
  cmake/externals/polyvox/CMakeLists.txt
  cmake/externals/quazip/CMakeLists.txt
  cmake/externals/sixense/CMakeLists.txt
  cmake/externals/steamworks/CMakeLists.txt
  cmake/externals/tbb/CMakeLists.txt
  cmake/externals/vhacd/CMakeLists.txt
  cmake/externals/wasapi/CMakeLists.txt
  cmake/ports/openssl-android/portfile.cmake
  cmake/ports/webrtc/portfile.cmake
  hifi_vcpkg.py
  launchers/qt/CMakeLists.txt
Labels: bug, enhancement

#23 Update Primary CMakeLists project name to Athena
  CMakeLists.txt
Labels: branding

#31 Audio Failure Due to missing VR fix
  plugins/openvr/src/OpenVrHelpers.cpp
Labels: bug

#37 Update interface window title
  interface/src/Application.cpp
Labels: good first issue

#32 Workaround for Secondary camera crash
  libraries/render/src/render/CullTask.cpp
Labels: bug

#38 Feature/quality of life k2
  README.md
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
  interface/resources/qml/hifi/dialogs/security/EntityScriptQMLWhitelist.qml
  interface/src/Application.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
Labels: documentation

#45 The command line no longer launches with interface.
  interface/CMakeLists.txt
Labels: bug

#16 QML Whitelisting
  interface/src/Application.cpp
Labels: enhancement
