Repository vircadia/vircadia-native-core, pull requests merged in 2020-10, with the labels that each got.

#730 API docs updates
  domain-server/src/DomainMetadata.h
  domain-server/src/DomainServer.h
  interface/src/Application.h
  libraries/entities/src/EntityScriptingInterface.h
  libraries/script-engine/src/ScriptEngine.h
  tools/jsdoc/plugins/hifiJSONExport.js
Labels: docs, rebuild

#761 Fix more warnings
  libraries/entities-renderer/src/RenderableGizmoEntityItem.h
  libraries/fbx/src/GLTFSerializer.cpp
Labels: CR Approved

#651 Update shortcut names to include "Vircadia"
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/CPackProperties.cmake.in
  cmake/templates/NSIS.template.in
Labels: CR Approved, QA Approved, enhancement, rebuild

#778 Open chat hyperlinks in Interface browser window
  .eslintrc.js
  interface/src/AboutUtil.cpp
  interface/src/AboutUtil.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  scripts/communityScripts/chat/FloofChat.js
Labels: CR Approved, QA Approved, enhancement, scripting api change

#669 add more details to messages logged in entity scripts
  interface/src/ui/LogDialog.cpp
  interface/src/ui/LogDialog.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/shared/src/shared/AbstractLoggerInterface.h
Labels: CR Approved, QA Approved, allow-build-upload, enhancement, rebuild

#763 Set GL preference to GLVND
  interface/CMakeLists.txt
  libraries/display-plugins/CMakeLists.txt
  libraries/gl/CMakeLists.txt
  libraries/gpu-gl-common/CMakeLists.txt
  libraries/gpu-gl/CMakeLists.txt
  libraries/qml/CMakeLists.txt
  libraries/ui/CMakeLists.txt
  tools/gpu-frame-player/CMakeLists.txt
Labels: CR Approved, QA Approved, enhancement

#546 Enable automatic avatar and audio mixer threading defaults
  domain-server/resources/web/wizard/index.shtml
  domain-server/resources/web/wizard/js/wizard.js
Labels: CR Approved, QA Approved, bugfix, domain-server

#737 Replacement of 3D Overlays for Local Entities
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
Labels: CR Approved, QA Approved, allow-build-upload, enhancement, rebuild

#677 Add option to capture mouse
  interface/resources/controllers/keyboardMouse.json
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/FancyCamera.h
  interface/src/ui/PreferencesDialog.cpp
  libraries/display-plugins/src/display-plugins/CompositorHelper.cpp
  libraries/display-plugins/src/display-plugins/CompositorHelper.h
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.cpp
  libraries/input-plugins/src/input-plugins/KeyboardMouseDevice.h
  libraries/shared/src/shared/Camera.h
Labels: CR Approved, QA Approved, enhancement, navigation, rebuild, scripting api change

#789 Update API docs to specify entity-server-script findEntities caveat.
  libraries/entities/src/EntityScriptingInterface.h
Labels: docs

#773 Fix handling of missing glTF blendshape target meshes
  libraries/fbx/src/GLTFSerializer.cpp
Labels: CR Approved, QA Approved, bugfix

#806 Set OpenGL_GL_PREFERENCE to LEGACY
  debian/rules
  interface/CMakeLists.txt
  libraries/display-plugins/CMakeLists.txt
  libraries/gl/CMakeLists.txt
  libraries/gpu-gl-common/CMakeLists.txt
  libraries/gpu-gl/CMakeLists.txt
  libraries/qml/CMakeLists.txt
  libraries/ui/CMakeLists.txt
  tools/gpu-frame-player/CMakeLists.txt
Labels: CR Approved, QA Approved, bugfix

#814 Rename field in Explore app's "add location" dialog
  scripts/communityScripts/explore/explore.html
  scripts/communityScripts/explore/explore.js
Labels: CR Approved, bugfix

#808 Workaround: Add Valve Index to calibratable devices
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
Labels: CR Approved, QA Approved, allow-build-upload, rebuild

#805 First run script.
  scripts/defaultScripts.js
  scripts/system/onFirstRun.js
Labels: CR Approved, QA Approved, enhancement

#760 Create App: HMD missing functionalities
  interface/resources/fonts/vircadia_glyphs.ttf
  scripts/system/create/audioFeedback/audioFeedback.js
  scripts/system/create/audioFeedback/sounds/confirmation.mp3
  scripts/system/create/audioFeedback/sounds/rejection.mp3
  scripts/system/create/edit.js
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
  scripts/system/create/qml/EditTabView.qml
  scripts/system/html/css/edit-style.css
Labels: CR Approved, QA Approved, allow-build-upload, enhancement

#821 Update decimatedTextureCount apidoc
  interface/src/ui/Stats.h
Labels: docs

#803 Hide temp place name button, hide places table, hide places wizard step.
  domain-server/resources/web/js/shared.js
  domain-server/resources/web/settings/js/settings.js
  domain-server/resources/web/wizard/index.shtml
  domain-server/resources/web/wizard/js/wizard.js
Labels: CR Approved, QA Approved, domain-server, enhancement, rebuild

#826 Append 'Vircadia' to the environment variable for the metadata exporter port
  libraries/networking/src/DomainHandler.h
Labels: CR Approved, domain-server, enhancement

#840 Prevent crash on entity-script-server due to logging interface.
  libraries/script-engine/src/ScriptEngine.cpp
Labels: CR Approved, QA Approved, bugfix, needs QA (testing)

#841 Housekeeping for attribution
  plugins/KasenAPIExample/src/ExampleScriptPlugin.h
  plugins/KasenAPIExample/src/KasenAPIExample.cpp
Labels: housekeeping

#844 Fix wrapping of "Enable Automatic Threading" in server setup wizard
  domain-server/resources/web/wizard/index.shtml
Labels: CR Approved, QA Approved, bugfix, domain-server

#613 [enhancement] transition listener registration from member string name to member string pointer
  assignment-client/src/Agent.cpp
  assignment-client/src/AssignmentClient.cpp
  assignment-client/src/AssignmentClientMonitor.cpp
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/entities/EntityServer.cpp
  assignment-client/src/messages/MessagesMixer.cpp
  assignment-client/src/octree/OctreeServer.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerSettingsManager.h
  interface/src/commerce/Wallet.cpp
  interface/src/octree/OctreePacketProcessor.cpp
  interface/src/scripting/ScreenshareScriptingInterface.cpp
  interface/src/ui/DomainConnectionModel.cpp
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/avatars/src/AvatarHashMap.cpp
  libraries/avatars/src/ClientTraitsHandler.cpp
  libraries/entities/src/EntityEditPacketSender.cpp
  libraries/entities/src/EntityScriptServerLogClient.cpp
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/networking/src/AssetClient.cpp
  libraries/networking/src/EntityScriptClient.cpp
  libraries/networking/src/MessagesClient.cpp
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/PacketReceiver.cpp
  libraries/networking/src/PacketReceiver.h
  libraries/networking/src/ResourceCache.cpp
  libraries/octree/src/OctreePersistThread.cpp
Labels: CR Approved, QA Approved, allow-build-upload, rebuild

#791 Qt 5.15 fixes: Initialize flags with default constructor
  libraries/ui/src/OffscreenUi.h
Labels: CR Approved, QA Approved, enhancement

#842 Hide "Secure Transactions" section in Settings > Security
  interface/resources/qml/hifi/dialogs/security/Security.qml
Labels: CR Approved, QA Approved, housekeeping

#804 Improve logging: color, ms timestamps, PID, thread id via environment variable
  libraries/shared/src/LogHandler.cpp
  libraries/shared/src/LogHandler.h
Labels: CR Approved, QA Approved, enhancement

#599 Initial version of automatic texture memory size
  libraries/gl/src/gl/Config.cpp
  libraries/gl/src/gl/Config.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLTextureTransfer.cpp
  libraries/gpu/src/gpu/Texture.h
  libraries/render-utils/src/text/Font.cpp
Labels: CR Approved, QA Approved, enhancement
