Repository vircadia/vircadia-native-core, pull requests merged in 2020-01, with the labels that each got.

#55 Fix scaled avatar walk speed
  interface/src/avatar/MyAvatar.cpp
Labels: bug

#56 Fix generating cmake
  hifi_vcpkg.py
Labels: bug

#43 Re-enable JSDoc building
  interface/CMakeLists.txt
Labels: bug, documentation

#67 Fixed clara rubbish
  interface/resources/qml/+webengine/QmlWebWindowView.qml
  interface/resources/qml/hifi/tablet/TabletRoot.qml
  interface/resources/qml/hifi/tablet/WindowRoot.qml
Labels: scripting-api-change

#66 Added ArrayBuffer support to websockets
  libraries/script-engine/src/WebSocketClass.cpp
  libraries/script-engine/src/WebSocketClass.h
Labels: enhancement, scripting-api-change

#65 Whitelist Quality of Life Updates
  libraries/script-engine/src/ScriptEngine.cpp
Labels: bug, enhancement

#69 Added FloofChat and Notification Core and put into defaultScripts.js
  scripts/communityModules/chat/FloofChat.html
  scripts/communityModules/chat/FloofChat.js
  scripts/communityModules/chat/FloofChat.qml
  scripts/communityModules/chat/chat.png
  scripts/communityModules/chat/css/FloofChat.css
  scripts/communityModules/chat/css/materialize.css
  scripts/communityModules/chat/js/materialize.min.js
  scripts/communityModules/notificationCore/notificationCore.js
  scripts/defaultScripts.js
Labels: enhancement

#47 Adapting some linux entries
  BUILD_LINUX.md
Labels: documentation

#75 Redo the interface's help menu for Project Athena.
  interface/resources/images/about-opus.png
  interface/resources/images/about-projectathena.png
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
  interface/src/Menu.cpp
Labels: Housekeeping, branding

#70 Rebranding of login dialogs etc. QML
  interface/resources/images/project-athena-banner-color2.svg
  interface/resources/qml/LoginDialog.qml
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
  interface/resources/qml/LoginDialog/UsernameCollisionBody.qml
  interface/src/workload/PhysicsBoundary.cpp
Labels: branding

#88 Added /l /d /g chatbar switches and /goto and /me
  scripts/communityModules/chat/FloofChat.html
  scripts/communityModules/chat/FloofChat.js
Labels: enhancement

#85 Removed obsolete default scripts + more branding changes.
  interface/src/Application.cpp
  libraries/entities/src/EntityItemProperties.cpp
  scripts/defaultScripts.js
  scripts/system/create/edit.js
Labels: branding, bug

#64 inspect.js improvements
  scripts/system/inspect.js
  scripts/system/libraries/entityCameraTool.js
Labels: enhancement

#33 Ability to change Metaverse API from setting
  assignment-client/src/avatars/MixerAvatar.cpp
  assignment-client/src/entities/EntityServer.cpp
  domain-server/src/DomainServer.cpp
  ice-server/src/IceServer.cpp
  interface/src/Application.cpp
  interface/src/commerce/Ledger.cpp
  interface/src/commerce/QmlCommerce.cpp
  interface/src/networking/CloseEventSender.cpp
  interface/src/ui/AddressBarDialog.h
  interface/src/ui/overlays/ContextOverlayInterface.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/networking/src/AccountManager.h
  libraries/networking/src/AssetUtils.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/FileResourceRequest.cpp
  libraries/networking/src/MetaverseAPI.cpp
  libraries/networking/src/MetaverseAPI.h
  libraries/networking/src/NetworkingConstants.cpp
  libraries/networking/src/NetworkingConstants.h
  libraries/networking/src/OAuthNetworkAccessManager.cpp
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/qml/src/qml/OffscreenSurface.cpp
  libraries/script-engine/src/XMLHttpRequestClass.cpp
  libraries/ui/src/ui/types/RequestFilters.cpp
  tools/ac-client/src/ACClientApp.cpp
  tools/atp-client/src/ATPClientApp.cpp
Labels: enhancement

#91 Re-branding of help dialogs and tablet login
  interface/resources/html/img/tablet-help-gamepad.jpg
  interface/resources/html/img/tablet-help-keyboard.jpg
  interface/resources/html/img/tablet-help-oculus.jpg
  interface/resources/html/img/tablet-help-vive.jpg
  interface/resources/html/img/tablet-help-windowsMR.jpg
  interface/resources/html/tabletHelp.html
  interface/resources/images/Loading-Inner-H.png
  interface/resources/qml/dialogs/TabletLoginDialog.qml
Labels: branding

#68 Fix thousands of 'is too small to hold all values' warnings on Linux
  libraries/gpu-gl-common/src/gpu/gl/GLBackendState.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLState.cpp
  libraries/gpu/src/gpu/Format.h
  libraries/gpu/src/gpu/State.cpp
  libraries/gpu/src/gpu/State.h
Labels: Housekeeping, renderer

#105 Update BUILD_LINUX.md
  BUILD_LINUX.md
Labels: documentation

#40 Rebranded Windows installer
  cmake/installer/installer-header.bmp
  cmake/installer/installer.ico
  cmake/installer/uninstaller-header.bmp
  cmake/macros/GenerateInstallers.cmake
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/NSIS.template.in
Labels: branding, enhancement

#115 API Docs now default to a brand new dark theme.
  tools/jsdoc/hifi-jsdoc-template/static/fonts/materialdesignicons-webfont.woff
  tools/jsdoc/hifi-jsdoc-template/static/fonts/materialdesignicons-webfont.woff2
  tools/jsdoc/hifi-jsdoc-template/static/scripts/vue.min.js
  tools/jsdoc/hifi-jsdoc-template/static/scripts/vue_dev.js
  tools/jsdoc/hifi-jsdoc-template/static/scripts/vuetify.js
  tools/jsdoc/hifi-jsdoc-template/static/styles/jsdoc.css
  tools/jsdoc/hifi-jsdoc-template/static/styles/materialdesignicons.min.css
  tools/jsdoc/hifi-jsdoc-template/static/styles/night.css
  tools/jsdoc/hifi-jsdoc-template/static/styles/vuetify.css
  tools/jsdoc/hifi-jsdoc-template/static/styles/vuetify.min.css
  tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl
Labels: enhancement

#118 APIDocs theme toggle bugfix
  tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl
Labels: documentation

#116 Replace links to docs.highfidelity.com
  interface/resources/qml/hifi/avatarapp/MessageBoxes.qml
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/Help.qml
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.h
  libraries/image/src/image/TextureProcessing.h
  libraries/midi/src/Midi.h
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/Vec3.h
Labels: bug, documentation

#119 Update API Docs for readability
  tools/jsdoc/hifi-jsdoc-template/static/styles/night.css
Labels: documentation

#112 Whitelist disabled by default, now has a toggle
  interface/resources/qml/hifi/dialogs/security/EntityScriptQMLWhitelist.qml
  interface/src/Menu.cpp
  libraries/script-engine/src/ScriptEngine.cpp
Labels: enhancement

#111 Support for short youtube url in linkify
  scripts/communityModules/chat/FloofChat.html
Labels: enhancement

#143 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#140 API Docs viewport restriction removal + menu toggle
  tools/jsdoc/hifi-jsdoc-template/static/styles/main.css
  tools/jsdoc/hifi-jsdoc-template/static/styles/responsive.css
  tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl
Labels: bug, documentation, enhancement
