Repository vircadia/vircadia-native-core, pull requests merged in 2020-04, with the labels that each got.

#253 Rebrand server console to Vircadia with Kasen icon.
  server-console/package.json
  server-console/packager.js
  server-console/resources/console-beta.icns
  server-console/resources/console-beta.ico
  server-console/resources/console-beta.png
  server-console/resources/console-notification.png
  server-console/resources/console-tray-osx-stopped.png
  server-console/resources/console-tray-osx-stopped@2x.png
  server-console/resources/console-tray-osx-stopping.png
  server-console/resources/console-tray-osx-stopping@2x.png
  server-console/resources/console-tray-osx.png
  server-console/resources/console-tray-osx@2x.png
  server-console/resources/console-tray-stopped.ico
  server-console/resources/console-tray-win-stopped.png
  server-console/resources/console-tray-win-stopped@2x.png
  server-console/resources/console-tray-win-stopping.png
  server-console/resources/console-tray-win-stopping@2x.png
  server-console/resources/console-tray-win.png
  server-console/resources/console-tray-win@2x.png
  server-console/resources/console-tray.ico
  server-console/resources/console.icns
  server-console/resources/console.ico
  server-console/resources/console.png
  server-console/src/content-update.html
  server-console/src/downloader.html
  server-console/src/images/console-hf-logo-2x.png
  server-console/src/main.js
  server-console/src/modules/hf-app.js
  server-console/src/splash.html
Labels: Housekeeping, PR-Win64_Build, branding

#255 V0.86.0 k2 -> kasen/core
  server-console/package.json
  server-console/packager.js
  server-console/resources/console-beta.icns
  server-console/resources/console-beta.ico
  server-console/resources/console-beta.png
  server-console/resources/console-notification.png
  server-console/resources/console-tray-osx-stopped.png
  server-console/resources/console-tray-osx-stopped@2x.png
  server-console/resources/console-tray-osx-stopping.png
  server-console/resources/console-tray-osx-stopping@2x.png
  server-console/resources/console-tray-osx.png
  server-console/resources/console-tray-osx@2x.png
  server-console/resources/console-tray-stopped.ico
  server-console/resources/console-tray-win-stopped.png
  server-console/resources/console-tray-win-stopped@2x.png
  server-console/resources/console-tray-win-stopping.png
  server-console/resources/console-tray-win-stopping@2x.png
  server-console/resources/console-tray-win.png
  server-console/resources/console-tray-win@2x.png
  server-console/resources/console-tray.ico
  server-console/resources/console.icns
  server-console/resources/console.ico
  server-console/resources/console.png
  server-console/src/content-update.html
  server-console/src/downloader.html
  server-console/src/images/console-hf-logo-2x.png
  server-console/src/main.js
  server-console/src/modules/hf-app.js
  server-console/src/splash.html
Labels: Housekeeping

#279 Fix VS2019 (Version 16.5.1) builds
  libraries/gpu/src/gpu/FrameReader.cpp
Labels: PR-Win64_Build, bug

#277 API docs rebranded to Vircadia.
  tools/jsdoc/api-mainpage.md
  tools/jsdoc/hifi-jsdoc-template/publish.js
  tools/jsdoc/hifi-jsdoc-template/static/images/fav-icon.ico
  tools/jsdoc/hifi-jsdoc-template/static/images/project-athena-logo.png
  tools/jsdoc/hifi-jsdoc-template/static/images/vircadia-logo-1880.png
  tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl
Labels: documentation

#287 Made Gridchat muted by default
  scripts/communityModules/chat/FloofChat.js
Labels: PR-Win64_Build, enhancement

#320 Miscellaneous JSdoc fixes
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/resources/qml/hifi/avatarapp/MessageBoxes.qml
  interface/src/avatar/MyAvatar.h
  interface/src/ui/InteractiveWindow.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars-renderer/src/avatars-renderer/ScriptAvatar.h
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/ScriptAvatarData.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.cpp
  libraries/graphics-scripting/src/graphics-scripting/GraphicsScriptingInterface.h
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMesh.h
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMeshPart.h
  libraries/graphics-scripting/src/graphics-scripting/ScriptableModel.h
  libraries/graphics/src/graphics/BufferViewHelpers.cpp
  libraries/shared/src/JointData.h
  libraries/shared/src/RegisteredMetaTypes.cpp
Labels: documentation
