Repository vircadia/vircadia-native-core, pull requests merged in 2020-03, with the labels that each got.

#175 Fix server logs filling up with "/"s
  libraries/networking/src/AddressManager.cpp
Labels: CR Approved, QA Approved, bug

#199 Fix button label and icon
  scripts/communityScripts/decentralizedGoTo/decentralizedGoTo.js
  scripts/communityScripts/decentralizedGoTo/explore-a.svg
  scripts/communityScripts/decentralizedGoTo/explore-i.svg
Labels: bug

#184 Updates the var name and URL for the goto JSON for use in chat
  scripts/communityModules/chat/FloofChat.js
Labels: CR Approved, QA Approved, bug

#192 Adds menu toggle for beta default scripts
  scripts/defaultScripts.js
Labels: CR Approved, QA Approved, enhancement

#190 Adds interim decentralizedGoTo as a default script, adds beta channel as well.
  scripts/communityScripts/decentralizedGoTo/addLocation.html
  scripts/communityScripts/decentralizedGoTo/bootstrap.min.css
  scripts/communityScripts/decentralizedGoTo/bootstrap.min.js
  scripts/communityScripts/decentralizedGoTo/decentralizedGoTo.html
  scripts/communityScripts/decentralizedGoTo/decentralizedGoTo.js
  scripts/communityScripts/decentralizedGoTo/explore-a.svg
  scripts/communityScripts/decentralizedGoTo/explore-i.svg
  scripts/communityScripts/decentralizedGoTo/explore.svg
  scripts/communityScripts/decentralizedGoTo/fancyTable.js
  scripts/communityScripts/decentralizedGoTo/goto-a-msg.svg
  scripts/communityScripts/decentralizedGoTo/goto-a.svg
  scripts/communityScripts/decentralizedGoTo/jquery.min.js
  scripts/defaultScripts.js
Labels: CR Approved, QA Approved, enhancement

#187 Add app-more.js to default scripts.
  scripts/defaultScripts.js
  scripts/system/more/app-more.js
  scripts/system/more/appicon_a.png
  scripts/system/more/appicon_i.png
  scripts/system/more/blank_minus-16.png
  scripts/system/more/blank_plus-16.png
  scripts/system/more/css/styles.css
  scripts/system/more/del-x-16.png
  scripts/system/more/minus-16.png
  scripts/system/more/more.html
  scripts/system/more/plus-16.png
  scripts/system/more/search-32.png
Labels: CR Approved, QA Approved, enhancement

#218 Add link to top of Entities API docs for the list of entity types.
  libraries/entities/src/EntityScriptingInterface.h
Labels: documentation

#219 Update license notice
  LICENSE
Labels: CR Approved, QA Approved, bug

#222 Fix updated TBB library hash in vcpkg portfile
  cmake/ports/tbb/portfile.cmake
Labels: CR Approved, QA Approved, bug

#237 Fix sidebar not showing on first load for API Docs
  tools/jsdoc/README.md
  tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl
  tools/jsdoc/plugins/hifi.js
Labels: bug, documentation

#101 Proposed rpm build spec
  pkg-scripts/Dockerfile.templ
  pkg-scripts/README
  pkg-scripts/athena-assignment-client.service
  pkg-scripts/athena-assignment-client@.service
  pkg-scripts/athena-domain-server.service
  pkg-scripts/athena-domain-server@.service
  pkg-scripts/athena-ice-server.service
  pkg-scripts/athena-ice-server@.service
  pkg-scripts/athena-server.spec
  pkg-scripts/athena-server.target
  pkg-scripts/athena-server@.target
  pkg-scripts/docker-athena-supervisor.conf
  pkg-scripts/docker-entrypoint.sh
  pkg-scripts/make-deb-server
  pkg-scripts/make-docker-server
  pkg-scripts/make-rpm-server
  pkg-scripts/new-server
  pkg-scripts/server-control
  pkg-scripts/server-postinst
  pkg-scripts/server-prerm
  pkg-scripts/server-rules
Labels: enhancement

#241 Update build docs.
  BUILD.md
  BUILD_ANDROID.md
  BUILD_LINUX.md
  BUILD_OSX.md
  BUILD_WIN.md
Labels: documentation

#242 Update install.md
  INSTALL.md
Labels: CR Approved, documentation

#247 Added license
  scripts/communityModules/chat/FloofChat.js
Labels: bug
