Repository vircadia/vircadia-native-core, pull requests merged in 2020-02, with the labels that each got.

#148 Fix browing JSDoc from file system in Edge browser
  tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl
Labels: documentation

#157 Various URL updates + window title update.
  interface/resources/qml/+webengine/BrowserWebView.qml
  interface/src/Application.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/ui/src/ui/TabletScriptingInterface.h
  script-archive/tests/performance/renderableMatrix.js
  scripts/system/create/edit.js
Labels: Housekeeping, documentation

#104 Make default copy constructors explicit
  interface/src/raypick/StylusPick.h
  libraries/animation/src/AnimInverseKinematics.h
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/SimulationOwner.h
  libraries/image/src/image/Image.h
  libraries/shared/src/CubicHermiteSpline.h
  libraries/shared/src/shared/MediaTypeLibrary.h
Labels: Housekeeping

#145 feature: Allow users to set avatar thumbnails that show in avatar app.
  interface/resources/qml/hifi/avatarapp/AvatarsModel.qml
Labels: enhancement

#167 Update README.md
  README.md
Labels: documentation

#170 Fix chat server relay
  scripts/communityModules/chat/FloofChat.js
Labels: bug

#160 Add support for serverless domains via HTTP/HTTPS
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/main.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/DomainHandler.cpp
  libraries/octree/src/Octree.cpp
  libraries/octree/src/Octree.h
Labels: bug, enhancement

#113 Always display vertical scrollbar in Settings dialogs that scroll
  interface/resources/qml/hifi/audio/Audio.qml
  interface/resources/qml/hifi/tablet/tabletWindows/TabletPreferencesDialog.qml
  interface/resources/qml/windows/ScrollingWindow.qml
Labels: bug

#177 Change to Project Athena in Task Manager
  interface/CMakeLists.txt
Labels: CR Approved, QA Approved, bug

#158 Force dynamic build on Linux
  cmake/init.cmake
  interface/CMakeLists.txt
Labels: CR Approved, QA Approved, bug

#162 Fix scripts not running at Interface start after reloading all scripts
  libraries/script-engine/src/ScriptEngines.cpp
Labels: CR Approved, QA Approved, bug

#179 Makes simplified nametag a default script
  scripts/defaultScripts.js
  scripts/simplifiedUI/ui/simplifiedNametag/simplifiedNametag.js
Labels: CR Approved, QA Approved, enhancement

#188 Add inspect.js to default scripts
  scripts/defaultScripts.js
Labels: CR Approved, QA Approved, enhancement
