Repository vircadia/vircadia-native-core, pull requests merged in 2020-05, with the labels that each got.

#257 Separate user activity logging from crash logging
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/main.cpp
  interface/src/ui/PreferencesDialog.cpp
  libraries/networking/src/UserActivityLogger.cpp
  libraries/networking/src/UserActivityLogger.h
Labels: Awaiting-Marcus-Build, QA Approved, enhancement

#334 Change standard snapshot name to vircadia
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/Snapshot.cpp
Labels: CR Approved, Housekeeping, QA Approved

#193 Create app: Properties editor: tabs
  scripts/system/create/entityProperties/html/entityProperties.html
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/entityProperties/html/tabs/base.png
  scripts/system/create/entityProperties/html/tabs/behavior.png
  scripts/system/create/entityProperties/html/tabs/collision.png
  scripts/system/create/entityProperties/html/tabs/grid.png
  scripts/system/create/entityProperties/html/tabs/image.png
  scripts/system/create/entityProperties/html/tabs/light.png
  scripts/system/create/entityProperties/html/tabs/material.png
  scripts/system/create/entityProperties/html/tabs/model.png
  scripts/system/create/entityProperties/html/tabs/particles.png
  scripts/system/create/entityProperties/html/tabs/particles_alpha.png
  scripts/system/create/entityProperties/html/tabs/particles_behavior.png
  scripts/system/create/entityProperties/html/tabs/particles_color.png
  scripts/system/create/entityProperties/html/tabs/particles_constraints.png
  scripts/system/create/entityProperties/html/tabs/particles_emit.png
  scripts/system/create/entityProperties/html/tabs/particles_size.png
  scripts/system/create/entityProperties/html/tabs/physics.png
  scripts/system/create/entityProperties/html/tabs/scripts.png
  scripts/system/create/entityProperties/html/tabs/shape.png
  scripts/system/create/entityProperties/html/tabs/spatial.png
  scripts/system/create/entityProperties/html/tabs/text.png
  scripts/system/create/entityProperties/html/tabs/web.png
  scripts/system/create/entityProperties/html/tabs/zone.png
  scripts/system/create/entityProperties/html/tabs/zone_ambient_light.png
  scripts/system/create/entityProperties/html/tabs/zone_avatar_priority.png
  scripts/system/create/entityProperties/html/tabs/zone_bloom.png
  scripts/system/create/entityProperties/html/tabs/zone_haze.png
  scripts/system/create/entityProperties/html/tabs/zone_key_light.png
  scripts/system/create/entityProperties/html/tabs/zone_skybox.png
  scripts/system/html/css/tabs.css
Labels: PR-Win64_Build, enhancement

#78 Zone occlusion
  interface/src/graphics/WorldBox.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityItemPropertiesMacros.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.cpp
  libraries/octree/src/OctreePacketData.h
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render/src/render/Args.h
  libraries/render/src/render/CullTask.cpp
  libraries/render/src/render/CullTask.h
  libraries/render/src/render/Item.cpp
  libraries/render/src/render/Item.h
  libraries/render/src/render/RenderFetchCullSortTask.cpp
  libraries/shared/src/RegisteredMetaTypes.cpp
  libraries/shared/src/RegisteredMetaTypes.h
Labels: CR Approved, PR-Win64_Build, QA Approved, documentation, enhancement, packet version change, question, renderer, scripting api change

#338 Bump packet version size up.
  libraries/networking/src/udt/PacketHeaders.h
Labels: bug

#339 Fix whitespace and line endings in tabs.css
  scripts/system/html/css/tabs.css
Labels: Housekeeping

#300 GitHub Actions (with artifact uploading)
  .github/workflows/pr_build.yml
  BUILD.md
  CMakeLists.txt
  cmake/macros/TargetDraco.cmake
  cmake/macros/TargetOpenEXR.cmake
  cmake/ports/glad/portfile.cmake
  cmake/ports/hifi-deps/CONTROL
  cmake/ports/polyvox/portfile.cmake
  cmake/ports/quazip/portfile.cmake
  cmake/ports/tbb/CONTROL
  cmake/ports/vhacd/portfile.cmake
  cmake/ports/zlib/CONTROL
  cmake/ports/zlib/cmake_dont_build_more_than_needed.patch
  hifi_qt.py
  hifi_utils.py
  hifi_vcpkg.py
  libraries/graphics/src/graphics/BufferViewHelpers.cpp
  libraries/graphics/src/graphics/BufferViewHelpers.h
  libraries/shared/CMakeLists.txt
  prebuild.py
  tools/ci-scripts/upload_to_publish_server.py
Labels: rebuild

#215 Feature/shape alpha
  scripts/system/create/assets/data/createAppTooltips.json
Labels: CR Approved, PR-Win64_Build, enhancement

#336 Improve information sent to Sentry on crashes
  interface/src/Application.cpp
  interface/src/CrashHandler_Crashpad.cpp
Labels: CR Approved, QA Approved, enhancement

#340 Attempt to fix #337 by ensuring the object is marked as dead.
  libraries/entities/src/EntityTree.cpp
Labels: bug

#301 Models support flipped normals on double sided geometry
  libraries/entities-renderer/src/paintStroke.slf
  libraries/graphics/src/graphics/Material.slh
  libraries/render-utils/src/CullFace.slh
  libraries/render-utils/src/model.slf
  libraries/render-utils/src/simple.slf
  libraries/render-utils/src/simple_procedural.slf
Labels: CR Approved, Housekeeping, QA Approved, bug, rebuild, renderer

#317 Don't let Linux build of glm with clang-9 fail due to stray semicolon
  cmake/ports/glm/disable_warnings_as_error.patch
Labels: allow-build-upload, rebuild

#344 Disable "grabbable" property by default
  scripts/system/create/edit.js
Labels: enhancement, rebuild

#346 Remove all uses of QString::null
  launchers/qt/src/BuildsRequest.h
  launchers/qt/src/LauncherState.cpp
  launchers/qt/src/LauncherState.h
  launchers/qt/src/UserSettingsRequest.h
  libraries/shared/src/PathUtils.h
  tools/oven/src/BakerCLI.h
  tools/oven/src/OvenCLIApplication.cpp
Labels: CR Approved

#296 Add community-apps repo to default QML whitelist.
  interface/src/Application.cpp
Labels: CR Approved, QA Approved, enhancement, rebuild

#335 Update to latest OpenVR SDK
  cmake/ports/openvr/portfile.cmake
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/OpenVrHelpers.cpp
Labels: CR Approved, QA Approved, enhancement

#373 Update More App to latest revision.
  scripts/system/more/app-more.js
  scripts/system/more/jquery-3.5.1.min.js
  scripts/system/more/more.html
Labels: CR Approved, enhancement

#391 Update INSTALL.md
  INSTALL.md
Labels: docs

#278 Docs + QML updates
  BUILD.md
  BUILD_LINUX_CHEATSHEET.md
  BUILD_OSX.md
  BUILD_WIN.md
  CODING_STANDARD.md
  CONTRIBUTING.md
  LICENSE
  README.md
  README_hifi.md
  android/apps/interface/src/main/res/values/strings.xml
  domain-server/resources/web/wizard/index.shtml
  interface/resources/html/commerce/backup_instructions.html
  interface/resources/html/tabletHelp.html
  interface/resources/qml/+webengine/BrowserWebView.qml
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
  interface/resources/qml/LoginDialog/UsernameCollisionBody.qml
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerApp.qml
  interface/resources/qml/hifi/avatarPackager/AvatarProject.qml
  interface/resources/qml/hifi/avatarapp/MessageBoxes.qml
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/Help.qml
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
  interface/src/Application.cpp
  interface/src/FancyCamera.h
  interface/src/Menu.cpp
  interface/src/avatar/AvatarDoctor.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/main.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/image/src/image/TextureProcessing.h
  libraries/midi/src/Midi.h
  libraries/networking/src/NetworkingConstants.h
  libraries/plugins/src/plugins/SteamClientPlugin.h
  libraries/render-utils/src/CullFace.slh
  libraries/script-engine/src/Quat.h
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/Vec3.h
  libraries/ui/src/ui/TabletScriptingInterface.h
  script-archive/afk.js
  script-archive/tests/performance/renderableMatrix.js
  script-archive/tutorials/fireworks/chapter1/fireworksLaunchButtonEntityScript.js
  script-archive/tutorials/fireworks/chapter1/fireworksLaunchButtonSpawner.js
  script-archive/tutorials/fireworks/chapter2/fireworksLaunchButtonEntityScript.js
  script-archive/tutorials/fireworks/chapter2/fireworksLaunchButtonSpawner.js
  script-archive/tutorials/fireworks/chapter3/fireworksLaunchButtonEntityScript.js
  script-archive/tutorials/fireworks/chapter3/fireworksLaunchButtonSpawner.js
  scripts/system/create/edit.js
  scripts/system/create/entityProperties/html/entityProperties.html
  scripts/system/html/css/tabs.css
  scripts/system/more/app-more.js
  scripts/system/more/css/styles.css
  scripts/system/more/more.html
  scripts/system/tablet-goto.js
  server-console/package.json
Labels: docs, housekeeping, merge right before snip

#369 Zones Selector sorted by zone names
  scripts/system/create/edit.js
Labels: CR Approved, QA Approved, allow-build-upload, bugfix, rebuild

#281 Improve performance of MyAvatar::simulate when you have lots of descendants
  interface/src/avatar/MyAvatar.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: CR Approved, QA Approved, enhancement, housekeeping, rebuild, renderer

#62 Support blendshapes on model entities
  libraries/avatars/src/HeadData.cpp
  libraries/avatars/src/HeadData.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/CauterizedModel.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
  libraries/render-utils/src/MeshPartPayload.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  libraries/render-utils/src/SoftAttachmentModel.cpp
  libraries/render/src/render/Item.h
  libraries/shared/src/BlendshapeConstants.cpp
  libraries/shared/src/BlendshapeConstants.h
  plugins/KasenAPIExample/src/KasenAPIExample.cpp
Labels: CR Approved, QA Approved, docs, enhancement, packet version change, rebuild, scripting api change
