Repository vircadia/vircadia-native-core, pull requests merged in 2020-11, with the labels that each got.

#833 Create Application: Improvements October 2020
  interface/resources/fonts/vircadia_glyphs.ttf
  scripts/system/create/edit.js
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
  scripts/system/create/qml/NewMaterialDialog.qml
  scripts/system/create/qml/NewModelDialog.qml
  scripts/system/html/css/edit-style.css
Labels: CR Approved, QA Approved, allow-build-upload, enhancement, rebuild

#719 GHA builds for merges to master
  .github/workflows/master_build.yml
  cmake/templates/NSIS.template.in
  tools/ci-scripts/upload.py
Labels: QA Approved, rebuild

#848 ScriptCache: add local file change detection
  libraries/networking/src/FileResourceRequest.cpp
  libraries/networking/src/ResourceRequest.cpp
  libraries/networking/src/ResourceRequest.h
  libraries/script-engine/src/ScriptCache.cpp
  libraries/script-engine/src/ScriptCache.h
Labels: CR Approved, QA Approved, allow-build-upload, enhancement

#846 Fix domain-server settings "Create new domain ID" dialog.
  domain-server/resources/web/settings/js/settings.js
Labels: CR Approved, QA Approved, bugfix, domain-server

#847 Example "modkit" JS Plugin renovation
  interface/resources/qml/hifi/dialogs/security/Security.qml
  plugins/CMakeLists.txt
  plugins/JSAPIExample/CMakeLists.txt
  plugins/JSAPIExample/src/JSAPIExample.cpp
  plugins/JSAPIExample/src/plugin.json
  plugins/KasenAPIExample/CMakeLists.txt
  plugins/KasenAPIExample/src/ExampleScriptPlugin.h
  plugins/KasenAPIExample/src/KasenAPIExample.cpp
  plugins/KasenAPIExample/src/plugin.json
Labels: CR Approved, QA Approved, allow-build-upload, enhancement, housekeeping

#853 Fix enterEntity event not firing in entity script after content reload
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: CR Approved, QA Approved, bugfix

#664 Feature/require redownload
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
Labels: CR Approved, QA Approved, enhancement, rebuild, scripting api change

#852 Enable username or e-mail for domain login
  domain-server/src/DomainGatekeeper.cpp
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
Labels: CR Approved, QA Approved, enhancement, rebuild

#858 Create App. - Feature Bundle - Nov 2020
  scripts/system/create/edit.js
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
  scripts/system/create/qml/EditTabView.qml
  scripts/system/create/qml/EditToolsTabView.qml
  scripts/system/html/css/edit-style.css
Labels: CR Approved, QA Approved, allow-build-upload, bugfix, enhancement, rebuild

#659 Split Local and owned Avatar Entity scripts into their own ScriptEngine
  assignment-client/src/scripts/EntityScriptServer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
Labels: CR Approved, QA Approved, enhancement, high risk, rebuild, threading/deadlock (beware)

#868 Revert "Split Local and owned Avatar Entity scripts into their own ScriptEngine"
  assignment-client/src/scripts/EntityScriptServer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
Labels: rebuild

#872 Replace set-env in PR GHA
  .github/workflows/pr_build.yml
Labels: bugfix

#615 Playing with GHA
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  android/build_android.sh
  android/containerized_build.sh
  android/docker/Dockerfile
  libraries/gl/src/gl/Config.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  prebuild.py
  scripts/system/quickGoto.js
Labels: CR Approved, QA Approved, allow-build-upload, rebuild

#881 Fix GHA master build target branch
  .github/workflows/master_build.yml
Labels: bugfix

#871 Revert "Revert "Split Local and owned Avatar Entity scripts into their own ScriptEngine""
  assignment-client/src/scripts/EntityScriptServer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngines.cpp
Labels: CR Approved, QA Approved, rebuild

#887 Fix getting the free VRAM on ATI cards
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
Labels: CR Approved, QA Approved, bugfix

#874 Fix new Zones appearing as parent of a ghost child
  scripts/system/create/edit.js
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
  scripts/system/create/modules/entityShapeVisualizer.js
Labels: CR Approved, QA Approved, allow-build-upload, bugfix, rebuild

#863 Upgrade tbb to fix a startup crash on Fedora 32 and later
  cmake/ports/tbb/portfile.cmake
Labels: QA Approved, bugfix
