Repository vircadia/vircadia-native-core, pull requests merged in 2020-09, with the labels that each got.

#586 Allow resolving relative urls when importing entities json
  libraries/octree/src/Octree.cpp
  libraries/octree/src/Octree.h
  libraries/octree/src/OctreeEntitiesFileParser.cpp
  libraries/octree/src/OctreeEntitiesFileParser.h
Labels: QA Approved, allow-build-upload, enhancement, needs CR (code review), rebuild

#276 Improving performance of entity updates
  interface/resources/qml/+android_interface/Stats.qml
  interface/resources/qml/Stats.qml
  interface/src/ui/Stats.cpp
  interface/src/ui/Stats.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableGizmoEntityItem.cpp
  libraries/entities-renderer/src/RenderableGizmoEntityItem.h
  libraries/entities-renderer/src/RenderableGridEntityItem.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/GizmoEntityItem.cpp
  libraries/entities/src/GizmoEntityItem.h
  libraries/entities/src/GridEntityItem.cpp
  libraries/entities/src/GridEntityItem.h
  libraries/entities/src/ImageEntityItem.cpp
  libraries/entities/src/ImageEntityItem.h
  libraries/entities/src/LightEntityItem.cpp
  libraries/entities/src/LightEntityItem.h
  libraries/entities/src/LineEntityItem.cpp
  libraries/entities/src/LineEntityItem.h
  libraries/entities/src/MaterialEntityItem.cpp
  libraries/entities/src/MaterialEntityItem.h
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/entities/src/ParticleEffectEntityItem.cpp
  libraries/entities/src/ParticleEffectEntityItem.h
  libraries/entities/src/PolyLineEntityItem.cpp
  libraries/entities/src/PolyLineEntityItem.h
  libraries/entities/src/PolyVoxEntityItem.cpp
  libraries/entities/src/PolyVoxEntityItem.h
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: CR Approved, QA Approved, bug, domain-server, high risk, housekeeping, rebuild, renderer, scripting api change

#672 Tidy JSON relative URLs importing code
  libraries/octree/src/Octree.cpp
  libraries/octree/src/OctreeEntitiesFileParser.cpp
  libraries/octree/src/OctreeEntitiesFileParser.h
Labels: CR Approved, QA Approved, housekeeping

#658 Feature/add update notififier
  scripts/communityScripts/chat/FloofChat.js
  scripts/defaultScripts.js
  scripts/system/checkForUpdates.js
  scripts/system/controllers/controllerModules/equipEntity.js
  scripts/system/libraries/networkingConstants.js
  scripts/system/libraries/utils.js
Labels: CR Approved, enhancement

#624 Add "About" JavaScript API and platform string
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
  interface/src/AboutUtil.h
  interface/src/Application.cpp
  scripts/system/interstitialPage.js
Labels: CR Approved, QA Approved, scripting api change

#631 Test moving to qt image error handling in avatar app
  interface/resources/qml/hifi/avatarapp/AvatarsModel.qml
Labels: CR Approved, QA Approved, allow-build-upload, bugfix, rebuild

#441 improve crashpad reporting of unhandled c++ exceptions
  interface/src/CrashHandler.h
  interface/src/CrashHandler_Breakpad.cpp
  interface/src/CrashHandler_Crashpad.cpp
  interface/src/CrashHandler_None.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/main.cpp
  libraries/shared/src/CrashHelpers.cpp
  libraries/shared/src/CrashHelpers.h
Labels: CR Approved, QA Approved, allow-build-upload, enhancement, rebuild

#639 Don't display domain log-in items unless relevant
  interface/src/Application.cpp
  interface/src/Menu.cpp
  libraries/networking/src/DomainAccountManager.cpp
  libraries/networking/src/DomainAccountManager.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/NodeList.cpp
Labels: CR Approved, QA Approved, enhancement

#671 Fix and extend glTF blendshapes support
  interface/src/ModelPackager.cpp
  libraries/avatars-renderer/src/avatars-renderer/Head.cpp
  libraries/fbx/src/FBXSerializer.cpp
  libraries/fbx/src/FST.cpp
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
  libraries/hfm/src/hfm/HFM.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/shared/src/BlendshapeConstants.cpp
  libraries/shared/src/BlendshapeConstants.h
Labels: CR Approved, QA Approved, bugfix, enhancement, model: gltf/glb

#309 Procedural Shader applies to entities other than target
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/render-utils/src/MeshPartPayload.cpp
Labels: CR Approved, QA Approved, bugfix, rebuild, renderer

#701 Fix for Issue 696. Create App - List refresh on updating image URL
  scripts/system/create/edit.js
Labels: CR Approved, QA Approved, allow-build-upload, bugfix, rebuild

#699 Fix pick rays not intersecting glTF models
  libraries/fbx/src/GLTFSerializer.cpp
Labels: CR Approved, QA Approved, bugfix

#689 Add open-in-external-browser button to web browser dialog
  interface/resources/qml/Browser.qml
Labels: CR Approved, QA Approved, bugfix, enhancement

#640 Add ability to package Interface with a custom startup location (also tacks on some build docs updates)
  BUILD.md
  INSTALL.md
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/BuildInfo.h.in
  interface/src/Application.cpp
  interface/src/Menu.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
  libraries/networking/src/NetworkingConstants.h
Labels: CR Approved, QA Approved, docs, enhancement

#311 [shutdown-deadlock] Restructure ContextAwareProfile from polling to notifications
  libraries/ui/src/ui/types/ContextAwareProfile.cpp
  libraries/ui/src/ui/types/ContextAwareProfile.h
Labels: CR Approved, QA Approved, allow-build-upload, enhancement, rebuild, threading/deadlock (beware)

#713 Fix audio output switching crash
  libraries/audio-client/src/AudioClient.cpp
Labels: CR Approved, QA Approved, bugfix, threading/deadlock (beware)

#705 Quiet warning for unused blendshapeCoefficients property
  libraries/entities/src/ModelEntityItem.cpp
Labels: CR Approved, QA Approved, bugfix

#715 Fix "Serverless" capitalization in title bar
  interface/src/Application.cpp
Labels: CR Approved

#667 apparent copy/paste bug on assignment-client parameters
  assignment-client/src/AssignmentClientApp.cpp
Labels: CR Approved, allow-build-upload, rebuild

#703 Feature: Create Material even without a URL.
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/edit.js
  scripts/system/create/qml/NewMaterialDialog.qml
  scripts/system/create/qml/NewModelDialog.qml
Labels: CR Approved, QA Approved, allow-build-upload, enhancement, rebuild

#656 Fix build of hifiSdl2 on GCC 10
  plugins/hifiSdl2/CMakeLists.txt
Labels: CR Approved, bugfix

#694 Support relative JSON URLs in model textures property
  libraries/entities/src/EntityItemProperties.cpp
  libraries/octree/src/OctreeEntitiesFileParser.cpp
Labels: CR Approved, QA Approved, bugfix

#718 Domain Metaverse Switching & Interface Support Improved
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/provider/EndpointUsersProvider.java
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/provider/UserStoryDomainProvider.java
  domain-server/resources/describe-settings.json
  domain-server/resources/web/js/shared.js
  domain-server/resources/web/settings/js/settings.js
  domain-server/resources/web/wizard/index.shtml
  domain-server/resources/web/wizard/js/wizard.js
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  domain-server/src/DomainServerSettingsManager.h
  ice-server/src/IceServer.cpp
  interface/src/Application.cpp
  interface/src/Constants.h
  interface/src/networking/CloseEventSender.cpp
  interface/src/scripting/ScreenshareScriptingInterface.cpp
  interface/src/ui/LoginDialog.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
  libraries/networking/src/MetaverseAPI.cpp
  libraries/networking/src/MetaverseAPI.h
  libraries/networking/src/NetworkingConstants.h
Labels: CR Approved, QA Approved, enhancement, rebuild

#743 Fix GLB files not being able to be added from Asset Server
  interface/resources/qml/hifi/AssetServer.qml
  interface/resources/qml/hifi/dialogs/TabletAssetServer.qml
Labels: CR Approved, QA Approved, bugfix

#738 Fix chat opening due to other users triggering
  scripts/communityScripts/chat/FloofChat.html
  scripts/communityScripts/notificationCore/notificationCore.js
Labels: CR Approved, QA Approved, bugfix, rebuild

#654 Updated the Explore app UI
  scripts/communityScripts/explore/addLocation.html
  scripts/communityScripts/explore/bootstrap.min.css
  scripts/communityScripts/explore/bootstrap.min.js
  scripts/communityScripts/explore/explore-a.svg
  scripts/communityScripts/explore/explore-i.svg
  scripts/communityScripts/explore/explore.html
  scripts/communityScripts/explore/explore.js
  scripts/communityScripts/explore/explore.svg
  scripts/communityScripts/explore/fancyTable.js
  scripts/communityScripts/explore/jquery.min.js
  scripts/communityScripts/libraries/materialdesignicons/README.md
  scripts/communityScripts/libraries/materialdesignicons/css/materialdesignicons.css
  scripts/communityScripts/libraries/materialdesignicons/css/materialdesignicons.css.map
  scripts/communityScripts/libraries/materialdesignicons/css/materialdesignicons.min.css
  scripts/communityScripts/libraries/materialdesignicons/css/materialdesignicons.min.css.map
  scripts/communityScripts/libraries/materialdesignicons/fonts/materialdesignicons-webfont.eot
  scripts/communityScripts/libraries/materialdesignicons/fonts/materialdesignicons-webfont.ttf
  scripts/communityScripts/libraries/materialdesignicons/fonts/materialdesignicons-webfont.woff
  scripts/communityScripts/libraries/materialdesignicons/fonts/materialdesignicons-webfont.woff2
  scripts/communityScripts/libraries/materialdesignicons/license.md
  scripts/communityScripts/libraries/materialdesignicons/package.json
  scripts/communityScripts/libraries/materialdesignicons/preview.html
  scripts/communityScripts/libraries/materialdesignicons/scss/_animated.scss
  scripts/communityScripts/libraries/materialdesignicons/scss/_core.scss
  scripts/communityScripts/libraries/materialdesignicons/scss/_extras.scss
  scripts/communityScripts/libraries/materialdesignicons/scss/_functions.scss
  scripts/communityScripts/libraries/materialdesignicons/scss/_icons.scss
  scripts/communityScripts/libraries/materialdesignicons/scss/_path.scss
  scripts/communityScripts/libraries/materialdesignicons/scss/_variables.scss
  scripts/communityScripts/libraries/materialdesignicons/scss/materialdesignicons.scss
  scripts/communityScripts/libraries/vue-router/vue-router.js
  scripts/communityScripts/libraries/vue/vue.min.js
  scripts/communityScripts/libraries/vuetify/attributes.json
  scripts/communityScripts/libraries/vuetify/tags.json
  scripts/communityScripts/libraries/vuetify/vuetify-v2.3.9.css
  scripts/communityScripts/libraries/vuetify/vuetify-v2.3.9.css.map
  scripts/communityScripts/libraries/vuetify/vuetify-v2.3.9.js
  scripts/communityScripts/libraries/vuetify/vuetify-v2.3.9.js.map
  scripts/communityScripts/libraries/vuetify/vuetify-v2.3.9.min.css
  scripts/communityScripts/libraries/vuetify/vuetify-v2.3.9.min.js
  scripts/communityScripts/libraries/vuetify/web-types.json
Labels: QA Approved, allow-build-upload, enhancement, rebuild

#632 Add --get-temp-name to domain-server invocation in creation of Docker
  pkg-scripts/docker-vircadia-supervisor.conf
Labels: CR Approved, allow-build-upload, rebuild

#349 Fix warnings emitted by GCC
  domain-server/src/DomainGatekeeper.cpp
  interface/src/avatar/OtherAvatar.cpp
  interface/src/ui/OctreeStatsDialog.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendState.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackendTransform.cpp
  libraries/graphics-scripting/src/graphics-scripting/ScriptableMeshPart.cpp
  libraries/image/src/image/CubeMap.cpp
  libraries/octree/src/OctreePacketData.cpp
  libraries/render-utils/src/RenderPipelines.cpp
  libraries/shared/src/BufferParser.h
  libraries/shared/src/GeometryUtil.cpp
  libraries/shared/src/avx2/BlendshapePacking_avx2.cpp
  libraries/shared/src/shared/ConicalViewFrustum.cpp
  plugins/KasenAPIExample/src/KasenAPIExample.cpp
Labels: CR Approved, enhancement, rebuild

#657 Fix build on qt 5.14
  assignment-client/src/audio/AudioMixerClientData.h
  assignment-client/src/audio/AudioMixerSlave.h
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.h
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/shared/src/RegisteredMetaTypes.h
  libraries/shared/src/TBBHelpers.h
Labels: enhancement

#605 Transparent Web Entities
  interface/resources/qml/+webengine/BrowserWebView.qml
  interface/resources/qml/Web3DSurface.qml
  interface/resources/qml/controls/+webengine/FlickableWebViewCore.qml
  interface/resources/qml/controls/FlickableWebViewCore.qml
  interface/resources/qml/controls/WebView.qml
  interface/src/avatar/MyAvatar.cpp
  interface/src/ui/ModelsBrowser.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/networking/src/NetworkingConstants.h
  libraries/networking/src/udt/PacketHeaders.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: CR Approved, QA Approved, enhancement, merge right before snip, packet version change

#767 Fix/3 0 wrap up
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/HifiUtils.java
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/fragment/LoginFragment.java
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/provider/EndpointUsersProvider.java
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/provider/UserStoryDomainProvider.java
  android/apps/interface/src/main/java/io/highfidelity/hifiinterface/task/DownloadProfileImageTask.java
  cmake/templates/NSIS.template.in
  domain-server/resources/describe-settings.json
  interface/resources/serverless/tutorial.json
Labels: CR Approved, hifi migration
