Repository vircadia/vircadia-native-core, pull requests merged in 2020-06, with the labels that each got.

#406 Bugfix: Create app now uses proper dimensions on create
  scripts/system/create/edit.js
Labels: CR Approved, QA Approved, bugfix

#416 Fix issues with glb urls
  libraries/fbx/src/GLTFSerializer.cpp
Labels: CR Approved, QA Approved, bugfix, rebuild

#394 Enable flying in VR by default
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
Labels: CR Approved, QA Approved, enhancement, rebuild

#410 Update packaging parameters for Vircadia
  cmake/macros/GenerateInstallers.cmake
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/NSIS.template.in
  interface/CMakeLists.txt
Labels: CR Approved, QA Approved, hifi migration

#418 Include <stdexcept> for building on Windows10 with Visual Studio 2019
  libraries/ktx/src/khronos/KHR.h
  libraries/shared/src/shared/Storage.h
Labels: CR Approved, allow-build-upload

#409 Bugfix: Add null check to entity render clearing to fix crash.
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
Labels: CR Approved, QA Approved, bugfix, rebuild

#431 Remove path from boilerplate in coding standard
  CODING_STANDARD.md
Labels: docs

#427 Feature/further rebranding
  CMakeLists.txt
  cmake/installer/installer-header.bmp
  cmake/installer/installer.ico
  cmake/installer/uninstaller-header.bmp
  interface/icon/interface-beta.icns
  interface/icon/interface-beta.ico
  interface/icon/interface.icns
  interface/icon/interface.ico
  interface/resources/html/img/tablet-help-gamepad.jpg
  interface/resources/html/img/tablet-help-keyboard.jpg
  interface/resources/html/img/tablet-help-oculus.jpg
  interface/resources/html/img/tablet-help-vive.jpg
  interface/resources/html/img/tablet-help-windowsMR.jpg
  interface/resources/html/tabletHelp.html
  interface/resources/images/about-vircadia.png
  interface/resources/images/vircadia-logo.svg
  interface/resources/qml/LoginDialog.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
  interface/resources/qml/LoginDialog/UsernameCollisionBody.qml
  interface/resources/qml/dialogs/TabletLoginDialog.qml
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
  interface/src/Application.cpp
  interface/src/Menu.cpp
  libraries/entities/src/EntityItemProperties.cpp
  server-console/resources/console-beta.icns
  server-console/resources/console-beta.ico
  server-console/resources/console-beta.png
  server-console/resources/console-notification.png
  server-console/resources/console-tray-osx-stopped.png
  server-console/resources/console-tray-osx-stopped@2x.png
  server-console/resources/console-tray-osx-stopping.png
  server-console/resources/console-tray-osx-stopping@2x.png
  server-console/resources/console-tray-osx.png
  server-console/resources/console-tray-osx@2x.png
  server-console/resources/console-tray-stopped.ico
  server-console/resources/console-tray-win-stopped.png
  server-console/resources/console-tray-win-stopped@2x.png
  server-console/resources/console-tray-win-stopping.png
  server-console/resources/console-tray-win-stopping@2x.png
  server-console/resources/console-tray-win.png
  server-console/resources/console-tray-win@2x.png
  server-console/resources/console-tray.ico
  server-console/resources/console.icns
  server-console/resources/console.ico
  server-console/resources/console.png
Labels: QA Approved, hifi migration

#429 Use newer opus to fix illegal instruction in libopusCodec.so
  cmake/ports/opus/portfile.cmake
Labels: QA Approved, bugfix, rebuild

#425 Fix not being able to delete entities in serverless domains
  libraries/entities/src/EntityScriptingInterface.cpp
Labels: CR Approved, QA Approved, bugfix

#426 Fix visibility of values in Wearables dialog
  interface/resources/qml/controlsUit/SpinBox.qml
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
  interface/resources/qml/hifi/avatarapp/Vector3.qml
Labels: CR Approved, QA Approved, bugfix, rebuild

#432 Reduce minimum inspect distance
  scripts/system/inspect.js
Labels: CR Approved, QA Approved, enhancement

#437 Update login overlay to Vircadia.
  interface/resources/qml/OverlayLoginDialog.qml
Labels: CR Approved, QA Approved, branding, hifi migration, rebuild

#439 Remove old goto, update Explore app.
  scripts/communityScripts/explore/explore.html
  scripts/communityScripts/explore/explore.js
  scripts/defaultScripts.js
Labels: CR Approved, QA Approved, enhancement, hifi migration

#440 Disable crash logger by default
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/networking/src/UserActivityLogger.h
Labels: CR Approved, enhancement

#445 Update README.md
  README.md
Labels: CR Approved, docs

#444 Fix/ual checkbox default
  interface/src/Menu.cpp
Labels: CR Approved, bugfix

#448 Merge 2020.2.1 into master
  interface/resources/qml/OverlayLoginDialog.qml
  interface/resources/qml/controlsUit/SpinBox.qml
  interface/resources/qml/hifi/avatarapp/AdjustWearables.qml
  interface/resources/qml/hifi/avatarapp/Vector3.qml
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/networking/src/UserActivityLogger.h
  scripts/communityScripts/explore/explore.html
  scripts/communityScripts/explore/explore.js
  scripts/defaultScripts.js
  scripts/system/inspect.js
Labels: housekeeping

#280 Add Prometheus exporter
  assignment-client/src/assets/AssetServer.cpp
  assignment-client/src/audio/AudioMixerClientData.cpp
  assignment-client/src/octree/OctreeServer.cpp
  assignment-client/src/octree/OctreeServer.h
  domain-server/resources/describe-settings.json
  domain-server/resources/prometheus_exporter/index.html
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/DomainServerExporter.cpp
  domain-server/src/DomainServerExporter.h
  libraries/embedded-webserver/src/HTTPManager.h
  libraries/networking/src/DomainHandler.h
Labels: CR Approved, QA Approved, enhancement, rebuild

#350 Vive PRO Eye support
  README.md
  cmake/ports/aristo/portfile.cmake
  cmake/ports/sranipal/CONTROL
  cmake/ports/sranipal/portfile.cmake
  interface/src/Application.h
  interface/src/ui/PreferencesDialog.cpp
  plugins/hifiLeapMotion/src/LeapMotionPlugin.cpp
  plugins/openvr/CMakeLists.txt
  plugins/openvr/src/ViveControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.h
  scripts/defaultScripts.js
  scripts/system/controllers/controllerDispatcher.js
  scripts/system/controllers/controllerModules/disableOtherModule.js
  scripts/system/controllers/controllerModules/farActionGrabEntity.js
  scripts/system/controllers/controllerModules/farGrabEntity.js
  scripts/system/controllers/controllerModules/farTrigger.js
  scripts/system/controllers/controllerModules/nearGrabEntity.js
  scripts/system/controllers/controllerModules/stylusInput.js
  scripts/system/controllers/controllerModules/trackedHandTablet.js
  scripts/system/controllers/controllerModules/trackedHandWalk.js
  scripts/system/controllers/controllerScripts.js
  scripts/system/html/css/miniHandTablet.css
  scripts/system/html/js/miniTablet.js
  scripts/system/html/miniHandsTablet.html
  scripts/system/libraries/WebTablet.js
  scripts/system/libraries/controllerDispatcherUtils.js
  scripts/system/miniTablet.js
Labels: CR Approved, QA Approved, VR, enhancement, rebuild

#377 Fix Linux default audio device debug messages
  libraries/audio-client/src/AudioClient.cpp
Labels: CR Approved, QA Approved

#384 Rebranding stuff
  cmake/installer/installer.ico
  interface/resources/images/Loading-Inner-H.png
  interface/resources/images/about-projectathena.png
  interface/resources/images/about-vircadia.png
  interface/resources/images/hifi-logo-blackish.svg
  interface/resources/images/hifi-logo.svg
  interface/resources/images/project-athena-banner-color2.svg
  interface/resources/images/vircadia-banner.svg
  interface/resources/images/vircadia-logo.svg
  interface/resources/qml/LoginDialog.qml
  interface/resources/qml/OverlayLoginDialog.qml
  interface/resources/qml/UpdateDialog.qml
  interface/resources/qml/dialogs/TabletLoginDialog.qml
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerHeader.qml
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
  interface/src/avatar/AvatarProject.h
  interface/src/main.cpp
  libraries/networking/src/MetaverseAPI.cpp
  libraries/networking/src/MetaverseAPI.h
  scripts/system/more/app-more.js
Labels: CR Approved, QA Approved, allow-build-upload, branding, docs, housekeeping, rebuild

#399 Fix various crashes/issues in controller scripting API
  libraries/controllers/src/controllers/UserInputMapper.cpp
  libraries/controllers/src/controllers/UserInputMapper.h
Labels: CR Approved, QA Approved, bugfix, rebuild

#438 Disable Certified Entity Auto Deletion
  libraries/entities/src/EntityTree.cpp
Labels: CR Approved, QA Approved, enhancement

#447 Fix reloading content in serverless domain
  libraries/networking/src/DomainHandler.cpp
Labels: CR Approved, QA Approved, bugfix

#442 Fix models not scaling correctly when loading due to timeout.
  scripts/system/create/edit.js
Labels: CR Approved, QA Approved, bugfix

#471 Update login screen dismissal
  domain-server/resources/web/favicon.ico
  interface/resources/qml/LoginDialog.qml
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
Labels: CR Approved, QA Approved, allow-build-upload, branding, hifi migration

#473 Fix code indentation
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
Labels: housekeeping

#478 Remove script that no longer exists created by the Vive Pro Eye PR.
  scripts/defaultScripts.js
Labels: CR Approved, bugfix

#482 v2020.2.2-rc -> master
  scripts/defaultScripts.js
Labels: housekeeping

#487 Update BUILD.md
  BUILD.md
Labels: docs

#476 Update More app from community apps repo
  scripts/system/more/app-more.js
  scripts/system/more/css/styles.css
Labels: CR Approved, housekeeping
