Repository vircadia/vircadia-native-core, pull requests merged in 2020-08, with the labels that each got.

#579 Feature/chat improvements noti
  scripts/communityScripts/chat/FloofChat.html
  scripts/communityScripts/chat/FloofChat.js
  scripts/communityScripts/notificationCore/notificationCore.js
Labels: CR Approved, QA Approved, enhancement

#594 Update default texture memory from Auto (1GB) -> Auto (2GB).
  libraries/gpu-gl-common/src/gpu/gl/GLTextureTransfer.cpp
Labels: enhancement

#595 Add graphics settings menu bar button.
  interface/src/PerformanceManager.cpp
  scripts/defaultScripts.js
  scripts/system/graphicsSettings.js
Labels: enhancement

#597 OAuth2 WordPress CR
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  domain-server/src/DomainServerSettingsManager.h
  interface/src/Application.cpp
Labels: enhancement, needs CR (code review)

#596 NSIS: uncheck by default sandbox autostart
  cmake/templates/NSIS.template.in
Labels: CR Approved, QA Approved, enhancement, rebuild

#591 OAuth2 WordPress
  domain-server/resources/describe-settings.json
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainGatekeeper.h
  domain-server/src/DomainServerSettingsManager.cpp
  domain-server/src/DomainServerSettingsManager.h
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/LoggingInBody.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ConnectionMonitor.cpp
  interface/src/Menu.cpp
  interface/src/ui/DialogsManager.cpp
  interface/src/ui/DialogsManager.h
  interface/src/ui/LoginDialog.cpp
  interface/src/ui/LoginDialog.h
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/DomainAccountManager.cpp
  libraries/networking/src/DomainAccountManager.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodeList.h
  libraries/networking/src/NodePermissions.h
Labels: enhancement

#603 Incremental suffix to cloned entities's name (issue #575)
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
Labels: CR Approved, QA Approved, allow-build-upload, rebuild

#604 New URL for default Particle and Image resource
  scripts/system/create/edit.js
Labels: CR Approved, QA Approved, allow-build-upload, bugfix, rebuild

#303 Re-enable and update code signing in the NSIS template.
  CMakeLists.txt
  cmake/templates/NSIS.template.in
Labels: enhancement, rebuild

#606 Change colorSpread color-picker and other small fixes
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/html/css/edit-style.css
Labels: CR Approved, QA Approved, allow-build-upload, bugfix, rebuild

#641 changed url for AC script examples from HiFi to Vircadia github
  domain-server/resources/web/assignment/placeholder.js
Labels: CR Approved, hifi migration

#652 Update BUILD.md
  BUILD.md
Labels: docs, enhancement

#465 Domain Metadata Exporter
  domain-server/resources/describe-settings.json
  domain-server/resources/metadata_exporter/index.html
  domain-server/src/DomainMetadata.cpp
  domain-server/src/DomainMetadata.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  libraries/networking/src/DomainHandler.h
Labels: CR Approved, QA Approved, domain-server, enhancement
