Repository vircadia/vircadia-native-core, pull requests merged in 2020-12, with the labels that each got.

#882 Fix JSDoc typo
  libraries/script-engine/src/Quat.h
Labels: bugfix, docs

#895 Fix references 'kasen/core' -> 'master'
  BUILD_LINUX.md
  hifi_qt.py
Labels: docs

#879 Initial add of crash report arg option.
  interface/src/main.cpp
Labels: CR Approved, enhancement, needs QA (testing)

#891 Fix hifi_qt.py reporting Ubuntu 20.04 as outdated
  hifi_qt.py
Labels: CR Approved, allow-build-upload, rebuild

#860 Fix alt key on Linux
  libraries/gl/src/gl/GLWidget.cpp
  libraries/gl/src/gl/GLWidget.h
Labels: CR Approved, allow-build-upload, needs QA (testing)

#894 Create App. - Feature Bundle - Dec 2020
  scripts/system/create/edit.js
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/qml/EditToolsTabView.qml
  scripts/system/html/css/edit-style.css
  scripts/system/libraries/gridTool.js
Labels: CR Approved, QA Approved, enhancement

#830 Entity update improvements 2
  interface/src/Application.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.h
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableGizmoEntityItem.cpp
  libraries/entities-renderer/src/RenderableGridEntityItem.cpp
  libraries/entities-renderer/src/RenderableGridEntityItem.h
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.h
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
  libraries/entities-renderer/src/RenderableZoneEntityItem.cpp
  libraries/entities-renderer/src/RenderableZoneEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/LightEntityItem.cpp
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/entities/src/PolyLineEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.h
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/entities/src/ZoneEntityItem.h
  libraries/physics/src/PhysicalEntitySimulation.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: CR Approved, QA Approved, bugfix, enhancement, high risk, rebuild, renderer, threading/deadlock (beware)

#878 Enable crash reporting on PR builds from GHA
  .github/workflows/pr_build.yml
Labels: CR Approved, QA Approved, enhancement, rebuild

#838 HUD overlay fixes and improvements
  interface/resources/qml/desktop/Desktop.qml
  interface/resources/qml/windows/Frame.qml
  interface/src/ui/OverlayConductor.cpp
  interface/src/ui/OverlayConductor.h
  libraries/display-plugins/src/display-plugins/CompositorHelper.cpp
  libraries/display-plugins/src/display-plugins/CompositorHelper.h
Labels: CR Approved, QA Approved, bugfix, enhancement, rebuild

#906 Fix/update references
  .github/workflows/pr_build.yml
  BUILD_ANDROID.md
  BUILD_LINUX.md
  BUILD_WIN.md
  CONTRIBUTING.md
  README.md
  android/containerized_build.sh
  android/docker/Dockerfile
  domain-server/resources/metadata_exporter/index.html
  domain-server/resources/web/assignment/placeholder.js
  hifi_qt.py
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
  interface/resources/qml/hifi/dialogs/security/EntityScriptQMLWhitelist.qml
  interface/resources/qml/hifi/dialogs/security/Security.qml
  libraries/networking/src/NetworkingConstants.h
  pkg-scripts/README
  pkg-scripts/server-control
  pkg-scripts/vircadia-server.spec
  plugins/JSAPIExample/src/JSAPIExample.cpp
  prebuild.py
  scripts/system/more/more.html
  server-console/package.json
Labels: CR Approved, allow-build-upload, docs, housekeeping, rebuild

#908 Update GitHub links
  cmake/ports/etc2comp/portfile.cmake
  cmake/ports/hifi-scribe/portfile.cmake
  cmake/ports/nvtt/portfile.cmake
Labels: CR Approved, housekeeping, rebuild

#917 Fix building with GLES 3.2 on Linux
  CMakeLists.txt
  cmake/ports/glad/portfile.cmake
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
Labels: CR Approved, QA Approved, allow-build-upload, rebuild

#919 Upgraded Oculus Mobile and Platform SDKs to latest (1.37.0 and 23.0.0)
  cmake/macros/TargetOculusMobile.cmake
  hifi_android.py
  libraries/oculusMobile/src/ovr/Helpers.h
  libraries/oculusMobile/src/ovr/VrHandler.cpp
  libraries/oculusMobilePlugin/src/OculusMobileControllerManager.cpp
Labels: CR Approved, allow-build-upload, enhancement, rebuild

#824 Remove "Console" options from Interface-only installer (Windows)
  INSTALLER.md
  README.md
  cmake/macros/OptionalWinExecutableSigning.cmake
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/NSIS.template.in
Labels: QA Approved, bugfix, enhancement

#907 Create app dec2020 material icons
  scripts/system/create/assets/images/icon-material.svg
  scripts/system/create/assets/images/icon-particles.svg
  scripts/system/create/assets/images/icon-point-light.svg
  scripts/system/create/assets/images/icon-spot-light.svg
  scripts/system/create/assets/images/icon-zone.svg
  scripts/system/create/edit.js
  scripts/system/create/modules/entityShapeVisualizer.js
  scripts/system/libraries/entityIconOverlayManager.js
Labels: CR Approved, QA Approved, enhancement, rebuild

#877 Send address and port with each metaverse heartbeat.
  domain-server/resources/describe-settings.json
  domain-server/resources/web/js/shared.js
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  libraries/networking/src/LimitedNodeList.cpp
Labels: CR Approved, QA Approved, allow-build-upload, bugfix, domain-server, enhancement, rebuild

#944 Possible fix for bad physics performance
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
Labels: CR Approved, QA Approved, bugfix, renderer
