Repository vircadia/vircadia-native-core, pull requests merged in 2020-07, with the labels that each got.

#459 Add Help > Tutorial menu item
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/Menu.cpp
  libraries/networking/src/AddressManager.h
Labels: CR Approved, QA Approved, bugfix, docs, enhancement

#481 Fix illegal instruction in libaudio.dylib on OSX
  libraries/shared/src/NumericalConstants.h
Labels: CR Approved, QA Approved, bugfix

#486 Improve wording of Sandbox's get/set private user data descriptions
  domain-server/resources/describe-settings.json
Labels: CR Approved, QA Approved

#497 Add ability to paste entities to any host type
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/scripting/ClipboardScriptingInterface.cpp
  interface/src/scripting/ClipboardScriptingInterface.h
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
Labels: CR Approved, QA Approved, enhancement, rebuild, scripting api change

#485 Fix/chat optimizations
  scripts/communityScripts/chat/FloofChat.html
  scripts/communityScripts/chat/FloofChat.js
  scripts/communityScripts/chat/FloofChat.qml
  scripts/communityScripts/chat/chat.png
  scripts/communityScripts/chat/css/FloofChat.css
  scripts/communityScripts/chat/css/materialize.css
  scripts/communityScripts/chat/js/materialize.min.js
  scripts/communityScripts/chat/resources/bubblepop.wav
  scripts/communityScripts/notificationCore/notificationCore.js
  scripts/defaultScripts.js
Labels: CR Approved, QA Approved, enhancement, rebuild

#498 Properly pause particles when you look away
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.cpp
  libraries/entities-renderer/src/RenderableParticleEffectEntityItem.h
Labels: CR Approved, QA Approved, bugfix, rebuild

#480 Prevent a crash for corrupted GLTF models.
  libraries/fbx/src/GLTFSerializer.cpp
Labels: CR Approved, QA Approved, bugfix

#435 Possible fix for entity server crash
  assignment-client/src/entities/EntityServer.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
Labels: CR Approved, QA Approved, bugfix, domain-server, rebuild, threading/deadlock (beware)

#474 Reduce Missing Joint Log Spam
  libraries/animation/src/AnimInverseKinematics.cpp
Labels: CR Approved, QA Approved, bugfix

#387 Build OpenVR plugin on Linux
  BUILD.md
  cmake/ports/hifi-client-deps/CONTROL
  cmake/ports/openvr/portfile.cmake
  plugins/openvr/CMakeLists.txt
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/OpenVrHelpers.cpp
  plugins/openvr/src/OpenVrHelpers.h
  plugins/openvr/src/ViveControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.h
Labels: CR Approved, QA Approved

#466 Change Android URLs to Linode bucket, old HiFi one is gone
  hifi_android.py
Labels: CR Approved, QA Approved, hifi migration

#468 Little "Audio" settings UI improvements
  interface/resources/qml/hifi/audio/Audio.qml
Labels: CR Approved, QA Approved, allow-build-upload, enhancement

#499 Update BUILD_OSX.md
  BUILD_OSX.md
Labels: CR Approved, QA Approved, docs

#504 Import entities now works on domains that you do not have rights on.
  interface/src/Application.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/entities/src/EntityTree.h
  libraries/octree/src/Octree.cpp
  libraries/octree/src/Octree.h
Labels: CR Approved, QA Approved, bugfix, rebuild

#505 Increase maximum texture size to 8192
  interface/src/ModelPackager.cpp
  libraries/hfm/src/hfm/HFM.h
  libraries/image/src/image/TextureProcessing.cpp
Labels: CR Approved, QA Approved, enhancement, renderer

#507 JS Doc update for enterEntity signal.
  libraries/entities/src/EntityScriptingInterface.h
Labels: CR Approved, allow-build-upload, docs

#526 V2020.2.2 rc -> master
  interface/resources/qml/hifi/audio/Audio.qml
Labels: housekeeping

#484 Add option to enable/disable Vive Pro Eye eye tracking
  cmake/ports/sranipal/portfile.cmake
  interface/resources/qml/hifi/tablet/ControllerSettings.qml
  interface/resources/qml/hifi/tablet/OpenVrConfiguration.qml
  plugins/openvr/src/ViveControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.h
Labels: CR Approved, QA Approved

#536 Housekeeping/update explore app
  scripts/communityScripts/explore/explore.js
Labels: CR Approved, housekeeping

#533 Update BUILD_OSX.md
  BUILD_OSX.md
Labels: docs, osx

#537 Update INSTALL.md
  INSTALL.md
Labels: docs

#524 Change strings, comments and folders to Vircadia rebrand
  interface/CMakeLists.txt
  launchers/darwin/CMakeLists.txt
  launchers/qt/CMakeLists.txt
  launchers/qt/resources/qml/HFControls/HFTextLogo.qml
  launchers/qt/src/Launcher.cpp
  launchers/qt/src/LauncherInstaller_windows.cpp
  launchers/qt/src/main.cpp
  launchers/win32/LauncherManager.cpp
  screenshare/packager.js
  tools/nitpick/src/TestRunnerDesktop.cpp
Labels: CR Approved, QA Approved, allow-build-upload, hifi migration, rebuild

#544 Update the connection failure dialog 'go to' -> 'explore'
  interface/resources/qml/ConnectionFailureDialog.qml
  interface/resources/qml/dialogs/TabletConnectionFailureDialog.qml
Labels: CR Approved, QA Approved, bugfix

#561 Make sure renderWithZones works on models on restart/reload
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
Labels: CR Approved, QA Approved, allow-build-upload, bugfix, rebuild, renderer

#520 Fix/move user agent
  assignment-client/src/avatars/ScriptableAvatar.cpp
  domain-server/src/DomainServer.cpp
  interface/resources/qml/controls/+webengine/FlickableWebViewCore.qml
  interface/src/Application.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.h
  interface/src/ui/ModelsBrowser.cpp
  libraries/auto-updater/src/AutoUpdater.cpp
  libraries/baking/src/JSBaker.cpp
  libraries/baking/src/ModelBaker.cpp
  libraries/baking/src/TextureBaker.cpp
  libraries/fbx/src/FSTReader.cpp
  libraries/networking/src/AccountManager.h
  libraries/networking/src/HTTPResourceRequest.cpp
  libraries/networking/src/NetworkingConstants.h
  libraries/networking/src/OAuthNetworkAccessManager.cpp
  libraries/networking/src/ResourceManager.cpp
  libraries/networking/src/SandboxUtils.cpp
  libraries/render-utils/src/text/Font.cpp
  libraries/script-engine/src/ScriptsModel.cpp
  libraries/script-engine/src/XMLHttpRequestClass.cpp
  libraries/shared/src/SharedUtil.h
  libraries/ui/src/ui/types/FileTypeProfile.cpp
  libraries/ui/src/ui/types/RequestFilters.cpp
Labels: CR Approved, QA Approved, docs, housekeeping, scripting api change

#521 Feature/inventory app
  scripts/system/inventory/.gitignore
  scripts/system/inventory/README.md
  scripts/system/inventory/babel.config.js
  scripts/system/inventory/dist/css/app.a93e8b1f.css
  scripts/system/inventory/dist/css/chunk-vendors.8540aa41.css
  scripts/system/inventory/dist/favicon.ico
  scripts/system/inventory/dist/index.html
  scripts/system/inventory/dist/inventory-a-msg.svg
  scripts/system/inventory/dist/inventory-a.svg
  scripts/system/inventory/dist/inventory-i-msg.svg
  scripts/system/inventory/dist/inventory-i.svg
  scripts/system/inventory/dist/inventory.js
  scripts/system/inventory/dist/js/app.a3555a80.js
  scripts/system/inventory/dist/js/app.a3555a80.js.map
  scripts/system/inventory/dist/js/chunk-vendors.a0f21a27.js
  scripts/system/inventory/dist/js/chunk-vendors.a0f21a27.js.map
  scripts/system/inventory/package-lock.json
  scripts/system/inventory/package.json
  scripts/system/inventory/public/favicon.ico
  scripts/system/inventory/public/index.html
  scripts/system/inventory/public/inventory-a-msg.svg
  scripts/system/inventory/public/inventory-a.svg
  scripts/system/inventory/public/inventory-i-msg.svg
  scripts/system/inventory/public/inventory-i.svg
  scripts/system/inventory/public/inventory.js
  scripts/system/inventory/src/App.vue
  scripts/system/inventory/src/assets/logo.png
  scripts/system/inventory/src/assets/logo.svg
  scripts/system/inventory/src/assets/styles/styles.css
  scripts/system/inventory/src/components/ItemIterator.vue
  scripts/system/inventory/src/components/NotUsing.vue
  scripts/system/inventory/src/main.js
  scripts/system/inventory/src/plugins/event-bus.js
  scripts/system/inventory/src/plugins/store.js
  scripts/system/inventory/src/plugins/vuetify.js
  scripts/system/inventory/vue.config.js
Labels: CR Approved, enhancement, housekeeping

#539 Fix avatar not displaying when recording is re-loaded
  assignment-client/src/Agent.cpp
Labels: CR Approved, QA Approved, bugfix, domain-server

#543 Fix shape alpha 0 issue
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
Labels: CR Approved, QA Approved, bugfix, renderer

#545 Fix display of FBX models with only one color for vertices
  libraries/fbx/src/FBXSerializer_Mesh.cpp
Labels: CR Approved, QA Approved, bugfix

#550 Increase graphics settings' resolution scale item maximum to 2.0
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
Labels: CR Approved, QA Approved, enhancement

#571 Domain login groups and "not authorized on domain"
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainGatekeeper.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodePermissions.h
Labels: domain-server, enhancement

#538 Delay taking snapshot further at low render rates
  scripts/system/snapshot.js
Labels: CR Approved, QA Approved, bugfix

#547 Fix lag on restart with scaled avatar
  interface/src/avatar/MyCharacterController.cpp
  interface/src/avatar/OtherAvatar.cpp
  libraries/physics/src/CharacterController.cpp
Labels: CR Approved, QA Approved, bugfix, housekeeping, rebuild

#564 renderWithZones works on import from JSON
  libraries/entities/src/EntityTree.cpp
Labels: CR Approved, QA Approved, allow-build-upload, bugfix, rebuild

#574 Fix --url command line parameter to work with both "=" and " "
  interface/src/Application.cpp
Labels: CR Approved, QA Approved, bugfix

#577 Feature/domain groups
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainGatekeeper.h
  domain-server/src/DomainServerSettingsManager.cpp
  domain-server/src/DomainServerSettingsManager.h
  libraries/networking/src/NodePermissions.h
Labels: enhancement
