Repository vircadia/vircadia-native-core, pull requests merged in 2021-03, with the labels that each got.

#1064 Fix OSX crash on shutdown
  interface/src/Application.cpp
  libraries/script-engine/src/ScriptEngine.cpp
Labels: CR Approved, QA Approved, bugfix, osx

#1066 Fix AnimInverseKinematics crash
  libraries/animation/src/AnimInverseKinematics.cpp
  libraries/animation/src/AnimSkeleton.cpp
  libraries/animation/src/AnimSkeleton.h
Labels: CR Approved, QA Approved, bugfix

#1033 Non-uniformly scaled sphere zones and models behave like ellipsoids (and fix EntityItem::contains sphere case)
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/ZoneEntityItem.cpp
  libraries/physics/src/ShapeFactory.cpp
  libraries/shared/src/ShapeInfo.cpp
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/modules/entityShapeVisualizer.js
Labels: CR Approved, QA Approved, bugfix, question, renderer

#1007 Add manual mode to noise reduction + add noise reduction threshold
  interface/resources/qml/hifi/audio/Audio.qml
  interface/src/scripting/Audio.cpp
  interface/src/scripting/Audio.h
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
Labels: CR Approved, QA Approved, enhancement, scripting api change

#1071 Fix privacy setting text
  interface/src/ui/PreferencesDialog.cpp
Labels: CR Approved, QA Approved, bugfix

#899 Add basic Linux server packaging instructions.
  BUILD.md
  INSTALLER.md
Labels: CR Approved, QA Approved, docs

#1049 Update Ubuntu 18.04 amd64 Qt to 5.15.2
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  hifi_qt.py
  tools/qt-builder/README.md
  tools/qt-builder/patches/aec.patch
  tools/qt-builder/patches/qtscript-crash-fix.patch
Labels: CR Approved, dependencies, docs, linux

#1044 Remove nvtt workaround from linux build docs
  BUILD_LINUX.md
Labels: docs, linux, needs CR (code review)

#1078 Define code block language to fix sphinx warnings
  BUILD.md
  BUILD_ANDROID.md
  BUILD_OSX.md
Labels: docs

#1013 triggerHapticPulse supports arbitrary device index instead of just two hands
  libraries/controllers/src/controllers/InputDevice.h
  libraries/controllers/src/controllers/ScriptingInterface.cpp
  libraries/controllers/src/controllers/ScriptingInterface.h
  libraries/controllers/src/controllers/UserInputMapper.cpp
  libraries/controllers/src/controllers/UserInputMapper.h
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.cpp
  libraries/input-plugins/src/input-plugins/TouchscreenVirtualPadDevice.h
  libraries/oculusMobilePlugin/src/OculusMobileControllerManager.cpp
  plugins/hifiSdl2/src/Joystick.cpp
  plugins/hifiSdl2/src/Joystick.h
  plugins/oculus/src/OculusControllerManager.cpp
  plugins/oculus/src/OculusControllerManager.h
  plugins/openvr/src/ViveControllerManager.cpp
  plugins/openvr/src/ViveControllerManager.h
Labels: CR Approved, QA Approved, docs, rebuild, scripting api change

#1082 Add ability to preload entity script whitelist
  BUILD.md
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/BuildInfo.h.in
  interface/src/Application.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/script-engine/src/ScriptEngines.h
  libraries/script-engine/src/ScriptGatekeeper.cpp
  libraries/script-engine/src/ScriptGatekeeper.h
Labels: CR Approved, QA Approved, enhancement

#1068 Set resource total size to content size when using a qrc:// resource
  libraries/networking/src/ResourceCache.cpp
Labels: CR Approved, QA Approved, bugfix

#1081 Rename to "Vircadia Server" and disable server shortcuts with Express install on Windows
  cmake/macros/GenerateInstallers.cmake
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/NSIS.template.in
  server-console/src/main.js
Labels: CR Approved, QA Approved, enhancement

#1094 Domain chat muted by default
  scripts/communityScripts/chat/FloofChat.js
Labels: CR Approved, QA Approved, enhancement

#1084 Add messaging mixer rate limiting per node functionality.
  assignment-client/src/messages/MessagesMixer.cpp
  assignment-client/src/messages/MessagesMixer.h
  domain-server/resources/describe-settings.json
Labels: CR Approved, QA Approved, domain-server, enhancement

#1097 Fix program log spam after using Audio dialog
  interface/resources/qml/hifi/audio/Audio.qml
Labels: CR Approved, QA Approved, bugfix

#1092 Implement Linux machine fingerprints
  libraries/networking/src/FingerprintUtils.cpp
Labels: CR Approved, enhancement, needs QA (testing)

#1047 Small optimisations and tidying related to MyAvatar
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/ui/PreferencesDialog.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars/src/AvatarData.cpp
  libraries/physics/src/CharacterController.cpp
Labels: CR Approved, QA Approved, allow-build-upload, enhancement, rebuild, scripting api change

#1050 Image Entities: fix keepAspectRatio, implement naturalDimensions
  libraries/baking/src/TextureBaker.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/ImageEntityItem.cpp
  libraries/entities/src/ImageEntityItem.h
  libraries/gpu/src/gpu/Texture.h
  libraries/gpu/src/gpu/Texture_ktx.cpp
  libraries/image/src/image/TextureProcessing.cpp
  libraries/image/src/image/TextureProcessing.h
  libraries/material-networking/src/material-networking/KTXCache.cpp
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/material-networking/src/material-networking/TextureCache.h
Labels: CR Approved, QA Approved, bugfix, docs, enhancement, question / review, renderer

#1117 Activate stale bot
  .github/stale.yml
Labels: housekeeping, needs CR (code review)

#1090 Add improved functionality for `Users.kick` API.
  domain-server/src/DomainServerSettingsManager.cpp
  interface/resources/qml/hifi/Pal.qml
  interface/src/Application.cpp
  interface/src/Application.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodeList.h
  libraries/networking/src/UserActivityLoggerScriptingInterface.h
  libraries/script-engine/src/UsersScriptingInterface.cpp
  libraries/script-engine/src/UsersScriptingInterface.h
  libraries/shared/src/ModerationFlags.h
Labels: CR Approved, QA Approved, domain-server, enhancement, scripting api change

#1123 Fix glTF vertex colors
  libraries/fbx/src/GLTFSerializer.cpp
  libraries/fbx/src/GLTFSerializer.h
Labels: CR Approved, QA Approved, bugfix

#1076 Material improvements
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableGizmoEntityItem.cpp
  libraries/entities-renderer/src/RenderableGizmoEntityItem.h
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.h
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.h
  libraries/gpu-gl-common/src/gpu/gl/GLBackendInput.cpp
  libraries/gpu-gl/src/gpu/gl41/GL41BackendInput.cpp
  libraries/gpu-gl/src/gpu/gl45/GL45BackendInput.cpp
  libraries/render-utils/src/GeometryCache.cpp
Labels: CR Approved, QA Approved, bugfix, enhancement, question / review, renderer
