Repository vircadia/vircadia-native-core, pull requests merged in 2021-11, with the labels that each got.

#1427 Add antialiasing setting.
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
  libraries/render-utils/src/AntialiasingEffect.cpp
  libraries/render-utils/src/AntialiasingEffect.h
Labels: enhancement, CR Approved, QA Approved, allow-build-upload

#1435 Fix mime type for serving .htm and .html files with the embedded webserver.
  libraries/embedded-webserver/src/HTTPManager.cpp
Labels: CR Approved, QA Approved, domain-server, bugfix

#1422 Changed preset framerates; Add "low power" preset.
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/src/PerformanceManager.cpp
  interface/src/PerformanceManager.h
  interface/src/scripting/PerformanceScriptingInterface.cpp
  interface/src/scripting/PerformanceScriptingInterface.h
  libraries/platform/src/platform/Profiler.cpp
  libraries/platform/src/platform/Profiler.h
Labels: enhancement, CR Approved, QA Approved, allow-build-upload

#1438 Fixed empty POST request to settings.json crashing the Domain server.
  libraries/embedded-webserver/src/HTTPConnection.cpp
Labels: rebuild, CR Approved, QA Approved, domain-server, allow-build-upload, bugfix

#1436 Require OpenSSL 1.1.0 during CMake.
  cmake/macros/TargetOpenSSL.cmake
  ice-server/CMakeLists.txt
  launchers/qt/CMakeLists.txt
Labels: enhancement, CR Approved, linux, CMake

#1424 Increase performance on macOS and Linux with CMake variables for optimization and architecture-specific options.
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  BUILD.md
  BUILD_LINUX.md
  BUILD_OSX.md
  CMakeLists.txt
  cmake/compiler.cmake
  cmake/ports/bullet3/portfile.cmake
  cmake/ports/opus/portfile.cmake
Labels: CR Approved, QA Approved, allow-build-upload, CMake

#1444 Create app: Script indicator toggles for both entity client & server scripts.
  scripts/system/create/entityList/entityList.js
Labels: enhancement, rebuild, CR Approved, QA Approved, allow-build-upload

#1429 WebRTC revisions and updates including the addition of secure connections.
  domain-server/resources/describe-settings.json
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/DomainServerSettingsManager.cpp
  interface/src/avatar/OtherAvatar.cpp
  libraries/networking/src/webrtc/WebRTCDataChannels.cpp
  libraries/networking/src/webrtc/WebRTCDataChannels.h
  libraries/networking/src/webrtc/WebRTCSignalingServer.cpp
  libraries/networking/src/webrtc/WebRTCSignalingServer.h
Labels: rebuild, CR Approved, QA Approved, web sdk, unmerged-dev

#1467 Fix SSL WebSocket Domain server crash.
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  BUILD.md
  BUILD_LINUX.md
  BUILD_OSX.md
  CMakeLists.txt
  README.md
  cmake/compiler.cmake
  cmake/macros/TargetOpenSSL.cmake
  cmake/ports/bullet3/portfile.cmake
  cmake/ports/opus/portfile.cmake
  ice-server/CMakeLists.txt
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/general/General.qml
  interface/src/CrashHandler_Crashpad.cpp
  interface/src/Menu.cpp
  interface/src/Menu.h
  interface/src/PerformanceManager.cpp
  interface/src/PerformanceManager.h
  interface/src/scripting/PerformanceScriptingInterface.cpp
  interface/src/scripting/PerformanceScriptingInterface.h
  interface/src/scripting/RenderScriptingInterface.cpp
  interface/src/scripting/RenderScriptingInterface.h
  launchers/qt/CMakeLists.txt
  libraries/embedded-webserver/src/HTTPConnection.cpp
  libraries/embedded-webserver/src/HTTPManager.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
  libraries/networking/src/webrtc/WebRTCSignalingServer.cpp
  libraries/platform/src/platform/Profiler.cpp
  libraries/platform/src/platform/Profiler.h
  libraries/render-utils/src/AntialiasingEffect.cpp
  libraries/render-utils/src/AntialiasingEffect.h
  prebuild.py
  screenshare/package-lock.json
  screenshare/package.json
  scripts/system/create/entityList/entityList.js
  scripts/system/inventory/package-lock.json
Labels: CR Approved, QA Approved, bugfix, unmerged-dev

#1475 Fix automatic texture memory bug.
  libraries/gpu-gl-common/src/gpu/gl/GLBackend.cpp
Labels: rebuild, CR Approved, QA Approved, allow-build-upload, bugfix

#1465 Fix for _meshStates.empty() assertion.
  libraries/render-utils/src/Model.cpp
Labels: CR Approved, needs QA (testing), bugfix
