Repository vircadia/vircadia-native-core, pull requests merged in 2021-01, with the labels that each got.

#928 VR fixes for: couldn't sit on the floor, wrong walk directions.
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  interface/src/avatar/MyCharacterController.cpp
  interface/src/avatar/MyCharacterController.h
  interface/src/avatar/MySkeletonModel.cpp
  interface/src/ui/AnimStats.cpp
  interface/src/ui/PreferencesDialog.cpp
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/physics/src/CharacterController.cpp
  libraries/physics/src/CharacterController.h
  libraries/shared/src/AvatarConstants.h
Labels: CR Approved, QA Approved, allow-build-upload, enhancement, scripting api change

#967 Update BUILD_WIN.md
  BUILD_WIN.md
Labels: docs

#953 Disable z-write for transparent draws
  interface/src/raypick/ParabolaPointer.cpp
  libraries/procedural/src/procedural/Procedural.cpp
  libraries/render-utils/src/GeometryCache.cpp
  libraries/render-utils/src/text/Font.cpp
Labels: CR Approved, QA Approved, allow-build-upload, enhancement

#982 Fix small typo in getPlatformTierNames()
  interface/src/scripting/PlatformInfoScriptingInterface.cpp
Labels: CR Approved, bugfix, scripting api change

#983 Updated Windows VCPKG that includes an alternative JOM download URL
  hifi_vcpkg.py
Labels: CR Approved, QA Approved, bugfix

#937 Skip repeated log entries
  libraries/shared/src/LogHandler.cpp
  libraries/shared/src/LogHandler.h
Labels: CR Approved, QA Approved, enhancement

#974 Add appreciate app as default app.
  scripts/defaultScripts.js
  scripts/system/appreciate/README.md
  scripts/system/appreciate/appreciate.jpg
  scripts/system/appreciate/appreciate_app.js
  scripts/system/appreciate/resource.json
  scripts/system/appreciate/resources/animations/Cheering.fbx
  scripts/system/appreciate/resources/animations/Clapping.fbx
  scripts/system/appreciate/resources/appreciate_ui.html
  scripts/system/appreciate/resources/css/style.css
  scripts/system/appreciate/resources/images/icons/appreciate-a.svg
  scripts/system/appreciate/resources/images/icons/appreciate-i.svg
  scripts/system/appreciate/resources/images/loadingSpinner.svg
  scripts/system/appreciate/resources/js/appreciate_ui.js
  scripts/system/appreciate/resources/js/jscolor.js
  scripts/system/appreciate/resources/sounds/claps/01.wav
  scripts/system/appreciate/resources/sounds/claps/02.wav
  scripts/system/appreciate/resources/sounds/claps/03.wav
  scripts/system/appreciate/resources/sounds/claps/04.wav
  scripts/system/appreciate/resources/sounds/claps/05.wav
  scripts/system/appreciate/resources/sounds/claps/06.wav
  scripts/system/appreciate/resources/sounds/claps/07.wav
  scripts/system/appreciate/resources/sounds/claps/08.wav
  scripts/system/appreciate/resources/sounds/claps/09.wav
  scripts/system/appreciate/resources/sounds/claps/10.wav
  scripts/system/appreciate/resources/sounds/claps/11.wav
  scripts/system/appreciate/resources/sounds/claps/12.wav
  scripts/system/appreciate/resources/sounds/claps/13.wav
  scripts/system/appreciate/resources/sounds/claps/14.wav
  scripts/system/appreciate/resources/sounds/claps/15.wav
  scripts/system/appreciate/resources/sounds/claps/16.wav
  scripts/system/appreciate/resources/sounds/whistles/01.wav
  scripts/system/appreciate/resources/sounds/whistles/02.wav
  scripts/system/appreciate/resources/sounds/whistles/03.wav
  scripts/system/appreciate/resources/sounds/whistles/04.wav
  scripts/system/appreciate/resources/sounds/whistles/05.wav
  scripts/system/appreciate/resources/sounds/whistles/06.wav
  scripts/system/appreciate/resources/sounds/whistles/07.wav
  scripts/system/appreciate/resources/sounds/whistles/08.wav
  scripts/system/appreciate/resources/sounds/whistles/09.wav
  scripts/system/appreciate/resources/sounds/whistles/10.wav
  scripts/system/appreciate/resources/sounds/whistles/11.wav
  scripts/system/appreciate/resources/sounds/whistles/12.wav
  scripts/system/appreciate/resources/sounds/whistles/13.wav
  scripts/system/appreciate/resources/sounds/whistles/14.wav
  scripts/system/appreciate/resources/sounds/whistles/15.wav
  scripts/system/appreciate/resources/sounds/whistles/16.wav
  scripts/system/appreciate/resources/sounds/whistles/17.wav
Labels: enhancement, rebuild

#975 Add "RELEASE_NAME" env variable.
  cmake/macros/SetPackagingParameters.cmake
  cmake/templates/BuildInfo.h.in
  interface/src/Application.cpp
Labels: CR Approved, enhancement, rebuild

#991 Remove requirement of admin / logged in to teleport to people nearby
  interface/resources/qml/hifi/NameCard.qml
Labels: CR Approved, QA Approved, enhancement
