Repository vircadia/vircadia-native-core, pull requests merged in 2021-08, with the labels that each got.

#1302 Fix QString::SplitBehavior deprecation, replace with Qt::
  interface/src/Application.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/networking/src/AssetResourceRequest.cpp
  libraries/render-utils/src/Model.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/shared/src/shared/FileUtils.cpp
Labels: CR Approved

#1300 Anonymous Web SDK connection to domain server
  domain-server/src/NodeConnectionData.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/webrtc/WebRTCDataChannels.cpp
Labels: CR Approved, QA Approved, web sdk

#1299 Fix a couple of WebRTC Doxygen typos
  libraries/networking/src/webrtc/WebRTCDataChannels.h
Labels: CR Approved, QA Approved, bugfix, web sdk

#1311 Copy resources to interface's exe directory
  interface/CMakeLists.txt
Labels: CR Approved, QA Approved

#1309 Log the location of the primary resources file
  interface/src/Application.cpp
Labels: CR Approved, QA Approved

#1301 Fix QDir::operator= is deprecated
  interface/src/Application.cpp
Labels: rebuild, CR Approved, QA Approved

#1293 Update supporter info for README.md.
  README.md
Labels: docs

#1303 Replace deprecated QAbstractsocket::error with QAbstractSocket::error…
  libraries/embedded-webserver/src/HTTPConnection.cpp
  libraries/networking/src/LimitedNodeList.cpp
Labels: rebuild, CR Approved, QA Approved

#1251 Add disable domain port auto discovery by assignment client option.
  assignment-client/src/AssignmentClient.cpp
  assignment-client/src/AssignmentClient.h
  assignment-client/src/AssignmentClientApp.cpp
  assignment-client/src/AssignmentClientApp.h
  assignment-client/src/AssignmentClientMonitor.cpp
  assignment-client/src/AssignmentClientMonitor.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodeList.h
  pkg-scripts/vircadia-assignment-client.service
  pkg-scripts/vircadia-assignment-client@.service
Labels: CR Approved, QA Approved, domain-server, bugfix

#1314 make HUD bubble/shield button optional
  scripts/system/bubble.js
Labels: enhancement, rebuild, CR Approved, QA Approved, allow-build-upload

#1315 Explore app metaverse api updates
  scripts/communityScripts/explore/explore.html
  scripts/communityScripts/libraries/axios/LICENSE
  scripts/communityScripts/libraries/axios/axios.min.js
Labels: enhancement, CR Approved, QA Approved, allow-build-upload

#1316 Create app - "Reset Rotation" button
  scripts/system/create/edit.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/html/css/edit-style.css
Labels: enhancement, rebuild, CR Approved, QA Approved

#1313 Assignment client WebRTC connections
  assignment-client/src/AssignmentClient.cpp
  assignment-client/src/AssignmentClient.h
  assignment-client/src/AssignmentClientMonitor.cpp
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  ice-server/src/IceServer.cpp
  libraries/networking/src/BaseAssetScriptingInterface.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NetworkPeer.cpp
  libraries/networking/src/Node.cpp
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodeList.h
  libraries/networking/src/NodeType.h
  libraries/networking/src/udt/NetworkSocket.cpp
  libraries/networking/src/udt/NetworkSocket.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/networking/src/udt/Socket.cpp
  libraries/networking/src/udt/Socket.h
  libraries/networking/src/webrtc/WebRTCDataChannels.cpp
  libraries/networking/src/webrtc/WebRTCDataChannels.h
  libraries/networking/src/webrtc/WebRTCSocket.cpp
  libraries/networking/src/webrtc/WebRTCSocket.h
Labels: enhancement, packet version change, CR Approved, QA Approved, web sdk
