Repository vircadia/vircadia-native-core, pull requests merged in 2021-09, with the labels that each got.

#1329 Update webapp branch to recent master
  CMakeLists.txt
  README.md
  assignment-client/src/AssignmentClient.cpp
  assignment-client/src/AssignmentClient.h
  assignment-client/src/AssignmentClientApp.cpp
  assignment-client/src/AssignmentClientApp.h
  assignment-client/src/AssignmentClientMonitor.cpp
  assignment-client/src/AssignmentClientMonitor.h
  hifi_qt.py
  interface/CMakeLists.txt
  interface/src/Application.cpp
  interface/src/Menu.cpp
  libraries/animation/CMakeLists.txt
  libraries/embedded-webserver/src/HTTPConnection.cpp
  libraries/entities-renderer/CMakeLists.txt
  libraries/entities/CMakeLists.txt
  libraries/entities/src/EntityTree.cpp
  libraries/image/CMakeLists.txt
  libraries/networking/src/AssetResourceRequest.cpp
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/NetworkingConstants.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodeList.h
  libraries/render-utils/CMakeLists.txt
  libraries/render-utils/src/Model.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/shared/CMakeLists.txt
  libraries/shared/src/shared/FileUtils.cpp
  pkg-scripts/vircadia-assignment-client.service
  pkg-scripts/vircadia-assignment-client@.service
  screenshare/package-lock.json
  scripts/communityScripts/explore/explore.html
  scripts/communityScripts/libraries/axios/LICENSE
  scripts/communityScripts/libraries/axios/axios.min.js
  scripts/system/bubble.js
  scripts/system/create/edit.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/html/css/edit-style.css
  tools/CMakeLists.txt
  tools/jsdoc/CMakeLists.txt
  tools/jsdoc/plugins/hifiJSONExport.js
  tools/nitpick/CMakeLists.txt
Labels: QA Approved, web sdk

#1322 Update OpenVR to 1.16.8.
  cmake/ports/openvr/CONTROL
  cmake/ports/openvr/portfile.cmake
  plugins/openvr/src/OpenVrHelpers.cpp
Labels: enhancement, CR Approved, QA Approved

#1326 Fix avatar crash
  libraries/physics/src/MultiSphereShape.cpp
Labels: CR Approved, QA Approved, bugfix

#1354 Get make-deb-server working again
  pkg-scripts/README.md
  pkg-scripts/make-deb-server
Labels: bugfix

#1356 Get "make-deb-server" working again with Qt changes to Vircadia builder.
  pkg-scripts/README.md
  pkg-scripts/make-deb-server
Labels: bugfix

#1360 Adjustment to Doc for "created" properties
  libraries/entities/src/EntityItemProperties.cpp
Labels: docs, housekeeping, bugfix

#1349 Set GL preference to GLVND
  interface/CMakeLists.txt
  libraries/display-plugins/CMakeLists.txt
  libraries/gl/CMakeLists.txt
  libraries/gpu-gl-common/CMakeLists.txt
  libraries/gpu-gl/CMakeLists.txt
  libraries/qml/CMakeLists.txt
  libraries/ui/CMakeLists.txt
  tools/gpu-frame-player/CMakeLists.txt
Labels: CR Approved, QA Approved, linux, CMake

#1352 Code Review: use of Q_DISABLE_COPY.
  assignment-client/src/audio/AvatarAudioStream.h
  interface/src/avatar/MyHead.h
  libraries/animation/src/AnimNodeLoader.h
  libraries/animation/src/AnimRandomSwitch.h
  libraries/animation/src/AnimStateMachine.h
  libraries/audio/src/AudioInjectorManager.h
  libraries/audio/src/InjectedAudioStream.h
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/HeadData.h
  libraries/networking/src/AccountManager.h
  libraries/networking/src/NLPacketList.h
  libraries/networking/src/Node.h
  libraries/networking/src/NodeList.h
  libraries/networking/src/udt/CongestionControl.h
  libraries/networking/src/udt/ControlPacket.h
  libraries/networking/src/udt/PacketList.h
  libraries/networking/src/udt/SendQueue.h
  libraries/shaders/src/shaders/Shaders.h
  libraries/ui/src/VrMenu.cpp
Labels: enhancement, allow-build-upload

#1366 Fix crash due to audio packet loss with PCM and zlib codecs.
  plugins/pcmCodec/CMakeLists.txt
  plugins/pcmCodec/src/PCMCodecManager.h
Labels: audio-mixer, CR Approved, QA Approved, bugfix

#1346 Add aarch64 Linux GHA builds.
  .github/workflows/pr_build.yml
  cmake/macros/TargetWebRTC.cmake
  cmake/ports/hifi-deps/CONTROL
  hifi_qt.py
  hifi_vcpkg.py
  libraries/shared/src/shared/WebRTC.h
  plugins/CMakeLists.txt
Labels: enhancement, CR Approved, linux, CMake

#1376 Use GLVND on GLES.
  libraries/gpu-gles/CMakeLists.txt
Labels: QA Approved, linux, CMake
