Repository vircadia/vircadia-native-core, pull requests merged in 2021-12, with the labels that each got.

#1411 Specify macOS SDK to 10.12 on GHA to solve crash when entering fullscreen.
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: rebuild, CR Approved, QA Approved, macos

#1468 Fix deprecated usage of multiple keys in QHash and QMap.
  interface/src/ModelPackager.cpp
  interface/src/ModelPackager.h
  interface/src/ui/Stats.cpp
  libraries/model-networking/src/model-networking/ModelCache.cpp
  libraries/model-serializers/src/FBXSerializer.cpp
  libraries/model-serializers/src/FST.cpp
  libraries/model-serializers/src/FST.h
  libraries/model-serializers/src/FSTReader.cpp
  libraries/model-serializers/src/FSTReader.h
  libraries/model-serializers/src/GLTFSerializer.cpp
  libraries/networking/src/ResourceCache.cpp
  libraries/networking/src/ResourceCache.h
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/script-engine/src/ScriptEngines.h
  libraries/shared/src/HifiConfigVariantMap.cpp
  libraries/shared/src/shared/HifiTypes.h
  libraries/task/src/task/Config.h
Labels: housekeeping, CR Approved, QA Approved

#1511 Update API examples to use "vircadia" in mapping names.
  interface/src/SpeechRecognizer.h
  libraries/controllers/src/controllers/ScriptingInterface.h
  libraries/controllers/src/controllers/impl/MappingBuilderProxy.h
  libraries/controllers/src/controllers/impl/RouteBuilderProxy.h
  libraries/networking/src/MessagesClient.h
Labels: docs, housekeeping, CR Approved

#1474 Remove <thread> library from main.cpp.
  interface/src/main.cpp
Labels: rebuild, housekeeping, CR Approved, QA Approved, allow-build-upload

#1340 Housekeeping: Update use of "auto" with plugin lists.
  assignment-client/src/Agent.cpp
  assignment-client/src/audio/AudioMixer.cpp
  assignment-client/src/scripts/EntityScriptServer.cpp
  interface/src/Application.cpp
  interface/src/ui/HMDToolsDialog.cpp
  libraries/audio-client/src/AudioClient.cpp
  libraries/plugins/src/plugins/InputConfiguration.cpp
  libraries/plugins/src/plugins/PluginManager.cpp
  libraries/plugins/src/plugins/PluginUtils.cpp
Labels: enhancement, rebuild, housekeeping, CR Approved, QA Approved, allow-build-upload

#1526 GHA: Disable compiler optimization on self-hosted runner.
  .github/workflows/pr_build.yml
Labels: rebuild, CR Approved

#1423 Separate rendering effect settings.
  interface/resources/qml/hifi/dialogs/graphics/GraphicsSettings.qml
Labels: enhancement, rebuild, CR Approved, QA Approved, allow-build-upload

#1473 Remove second argument from some playSystemSound() calls in QML.
  interface/resources/qml/hifi/audio/PlaySampleSound.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/audio/Audio.qml
  interface/resources/qml/hifi/simplifiedUI/settingsApp/vr/VR.qml
  interface/src/avatar/MyAvatar.h
Labels: housekeeping, CR Approved, allow-build-upload, needs QA (testing)

#1533 Explore App: Use the placename instead of address (ip:port).
  scripts/communityScripts/explore/explore.html
Labels: enhancement, CR Approved, QA Approved

#1519 Create App - "Add All Zones" on renderWithZones selector.
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/modules/brokenURLReport.js
  scripts/system/html/css/edit-style.css
Labels: enhancement, CR Approved, QA Approved, allow-build-upload

#1523 Create App: Prevent locked entities and their children from being duplicated.
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
Labels: CR Approved, QA Approved, bugfix

#1548 Fix macOS SDK links in GHA.
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: bugfix, macos

#1528 GHA: Add checksum for macOS SDK for PR and master builds.
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: enhancement, macos

#1545 Update loops to prevent crash on some GLTF models.
  libraries/model-serializers/src/GLTFSerializer.cpp
Labels: rebuild, CR Approved, QA Approved, allow-build-upload, bugfix, model: gltf/glb

#1482 Replace the deprecated QVector::fromStdVector and QVector::toStdVector().
  libraries/model-baker/src/model-baker/Baker.cpp
  libraries/model-baker/src/model-baker/CalculateBlendshapeNormalsTask.cpp
  libraries/model-baker/src/model-baker/CalculateBlendshapeTangentsTask.cpp
  libraries/model-baker/src/model-baker/CalculateMeshNormalsTask.cpp
  libraries/model-baker/src/model-baker/CalculateMeshTangentsTask.cpp
  libraries/model-serializers/src/GLTFSerializer.cpp
Labels: rebuild, housekeeping, CR Approved, QA Approved

#1546 Update qt-builder readme for macOS
  tools/qt-builder/README.md
Labels: docs, macos

#1547 Remove extended deadlock wait on macOS
  interface/src/Application.cpp
Labels: rebuild, housekeeping, CR Approved, needs QA (testing), macos

#1552 Fixed metallic material import for glTF.
  libraries/model-serializers/src/GLTFSerializer.cpp
Labels: rebuild, CR Approved, allow-build-upload, needs QA (testing), bugfix

#1554 Choose right Qt version for Linux Mint 19.x
  hifi_qt.py
Labels: CR Approved, QA Approved, allow-build-upload, linux
