Repository vircadia/vircadia-native-core, pull requests merged in 2021-05, with the labels that each got.

#1183 ReadyPlayerMe blendshapes support
  libraries/model-serializers/src/GLTFSerializer.cpp
  libraries/shared/src/BlendshapeConstants.cpp
  libraries/shared/src/BlendshapeConstants.h
Labels: CR Approved, QA Approved, enhancement

#1196 Fix non-consecutive header level increases in build docs
  BUILD.md
  BUILD_OSX.md
  BUILD_WIN.md
Labels: CR Approved, docs

#1199 Fix GitHub Actions merge-to-master MacOS build
  .github/workflows/master_build.yml
Labels: CR Approved, bugfix

#1213 Create app: Copy-Paste Position and Rotation
  scripts/system/create/edit.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/html/css/edit-style.css
Labels: CR Approved, QA Approved, enhancement, rebuild

#1217 Fix missed JSDoc tag change
  libraries/oculusMobilePlugin/src/OculusMobileControllerManager.cpp
Labels: CR Approved

#1220 Fix typo in Doxygen ReadMe
  tools/doxygen/README.md
Labels: CR Approved, docs

#1218 Add patch for building Qt 5.15 on gcc11
  tools/qt-builder/patches/qt5.15-gcc11.patch
Labels: CR Approved, linux

#1225 fix PR autobuild for ubuntu-18.04, android with correct cmake version
  .github/workflows/pr_build.yml
Labels: Android, CR Approved, allow-build-upload, bugfix

#1226 Add "gren" configuration for easy changelog generation
  .grenrc.js
Labels: docs, enhancement

#1231 Add URL for .grenrc.js repository
  .grenrc.js
Labels: CR Approved
