Repository vircadia/vircadia-native-core, pull requests merged in 2021-07, with the labels that each got.

#1268 Don't use LeapMotion by default.
  plugins/hifiLeapMotion/CMakeLists.txt
Labels: CR Approved, QA Approved, enhancement

#1267 Fix CMake GifCreator name warning
  cmake/modules/FindGifCreator.cmake
Labels: CR Approved, QA Approved

#1266 Update Doxygen group tags to use /// format
  libraries/script-engine/src/AbstractScriptingServicesInterface.h
  libraries/script-engine/src/ArrayBufferClass.h
  libraries/script-engine/src/ArrayBufferPrototype.h
  libraries/script-engine/src/ArrayBufferViewClass.h
  libraries/script-engine/src/AssetScriptingInterface.h
  libraries/script-engine/src/AudioScriptingInterface.h
  libraries/script-engine/src/BatchLoader.h
  libraries/script-engine/src/ConsoleScriptingInterface.h
  libraries/script-engine/src/DataViewClass.h
  libraries/script-engine/src/DataViewPrototype.h
  libraries/script-engine/src/EventTypes.h
  libraries/script-engine/src/FileScriptingInterface.h
  libraries/script-engine/src/KeyEvent.h
  libraries/script-engine/src/MIDIEvent.h
  libraries/script-engine/src/Mat4.h
  libraries/script-engine/src/MenuItemProperties.h
  libraries/script-engine/src/ModelScriptingInterface.h
  libraries/script-engine/src/MouseEvent.h
  libraries/script-engine/src/Quat.h
  libraries/script-engine/src/RecordingScriptingInterface.h
  libraries/script-engine/src/SceneScriptingInterface.h
  libraries/script-engine/src/ScriptAudioInjector.h
  libraries/script-engine/src/ScriptCache.h
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngineLogging.h
  libraries/script-engine/src/ScriptEngines.h
  libraries/script-engine/src/ScriptGatekeeper.h
  libraries/script-engine/src/ScriptUUID.h
  libraries/script-engine/src/ScriptsModel.h
  libraries/script-engine/src/ScriptsModelFilter.h
  libraries/script-engine/src/SpatialEvent.h
  libraries/script-engine/src/StackTestScriptingInterface.h
  libraries/script-engine/src/TouchEvent.h
  libraries/script-engine/src/TypedArrayPrototype.h
  libraries/script-engine/src/TypedArrays.h
  libraries/script-engine/src/UsersScriptingInterface.h
  libraries/script-engine/src/Vec3.h
  libraries/script-engine/src/WebSocketClass.h
  libraries/script-engine/src/WebSocketServerClass.h
  libraries/script-engine/src/WheelEvent.h
  libraries/script-engine/src/XMLHttpRequestClass.h
  tools/doxygen/README.md
Labels: CR Approved, QA Approved, docs

#1255 Fix nvtt on x86
  cmake/ports/nvtt/0001-Build-on-aarch64.patch
  cmake/ports/nvtt/0002-Hack-remove-include-sysctl.h-to-build-on-linux-a.patch
  cmake/ports/nvtt/portfile.cmake
Labels: CMake, CR Approved, QA Approved, bugfix

#1275 Fix for nvtt on MacOS
  cmake/ports/nvtt/portfile.cmake
Labels: CR Approved, bugfix, rebuild

#1277 Quiet Doxygen output
  tools/doxygen/Doxyfile
Labels: CR Approved, QA Approved

#1276 GitHub Actions do not clone submodules
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: CR Approved, QA Approved

#1285 Reduce stale-bot's aggressiveness.
  .github/stale.yml
Labels: CR Approved, enhancement

#1283 Rename "HifiSockAddr" to "SockAddr"
  assignment-client/src/AssignmentClient.cpp
  assignment-client/src/AssignmentClient.h
  assignment-client/src/AssignmentClientMonitor.cpp
  assignment-client/src/avatars/AvatarMixer.cpp
  assignment-client/src/avatars/AvatarMixer.h
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainGatekeeper.h
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  domain-server/src/DomainServerNodeData.h
  domain-server/src/NodeConnectionData.cpp
  domain-server/src/NodeConnectionData.h
  ice-server/src/IceServer.cpp
  ice-server/src/IceServer.h
  libraries/audio-client/src/AudioClient.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/NLPacket.cpp
  libraries/networking/src/NLPacket.h
  libraries/networking/src/NetworkPeer.cpp
  libraries/networking/src/NetworkPeer.h
  libraries/networking/src/Node.cpp
  libraries/networking/src/Node.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodeList.h
  libraries/networking/src/PacketReceiver.cpp
  libraries/networking/src/PacketReceiver.h
  libraries/networking/src/ReceivedMessage.cpp
  libraries/networking/src/ReceivedMessage.h
  libraries/networking/src/SockAddr.cpp
  libraries/networking/src/SockAddr.h
  libraries/networking/src/udt/BasePacket.cpp
  libraries/networking/src/udt/BasePacket.h
  libraries/networking/src/udt/Connection.cpp
  libraries/networking/src/udt/Connection.h
  libraries/networking/src/udt/ControlPacket.cpp
  libraries/networking/src/udt/ControlPacket.h
  libraries/networking/src/udt/Packet.cpp
  libraries/networking/src/udt/Packet.h
  libraries/networking/src/udt/PacketList.cpp
  libraries/networking/src/udt/PacketList.h
  libraries/networking/src/udt/SendQueue.cpp
  libraries/networking/src/udt/SendQueue.h
  libraries/networking/src/udt/Socket.cpp
  libraries/networking/src/udt/Socket.h
  tests/networking/src/PacketTests.cpp
  tools/ice-client/src/ICEClientApp.cpp
  tools/ice-client/src/ICEClientApp.h
  tools/udt-test/src/UDTTest.cpp
  tools/udt-test/src/UDTTest.h
Labels: CR Approved, enhancement

#365 Linux crash handler
  cmake/externals/crashpad/CMakeLists.txt
  cmake/macros/AddCrashpad.cmake
  cmake/modules/FindCrashpad.cmake
  interface/src/CrashHandler.h
  interface/src/CrashHandler_Crashpad.cpp
  interface/src/CrashHandler_None.cpp
Labels: CR Approved, enhancement, rebuild

#1244 Add ability for 'handleLookupString' to have spaces.
  interface/src/Application.cpp
  interface/src/main.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/NetworkingConstants.h
  libraries/networking/src/NodeList.cpp
  libraries/script-engine/src/ScriptEngine.cpp
Labels: CR Approved, QA Approved, bugfix

#1274 Archive cmake logs, for debugging
  .github/workflows/pr_build.yml
Labels: CR Approved, QA Approved, enhancement, rebuild

#1289 Fix "Ninja does not support toolset specification" on Windows
  CMakeLists.txt
Labels: CMake, CR Approved, bugfix, windows

#1102 Material improvements 2: reference textures/materials by entity ID
  interface/src/Application.cpp
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableImageEntityItem.cpp
  libraries/entities-renderer/src/RenderableImageEntityItem.h
  libraries/entities-renderer/src/RenderableMaterialEntityItem.cpp
  libraries/entities-renderer/src/RenderableMaterialEntityItem.h
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityTree.cpp
  libraries/gpu/src/gpu/Texture.cpp
  libraries/gpu/src/gpu/Texture.h
  libraries/graphics/src/graphics/Material.cpp
  libraries/graphics/src/graphics/Material.h
  libraries/graphics/src/graphics/TextureMap.cpp
  libraries/material-networking/src/material-networking/TextureCache.cpp
  libraries/material-networking/src/material-networking/TextureCache.h
  libraries/procedural/src/procedural/Procedural.h
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.h
  libraries/procedural/src/procedural/ReferenceMaterial.cpp
  libraries/procedural/src/procedural/ReferenceMaterial.h
  libraries/render-utils/src/RenderPipelines.cpp
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: CR Approved, QA Approved, bugfix, docs, enhancement, renderer

#1270 Replace uses of endl on Qt classes with Qt::endl
  android/apps/interface/src/main/cpp/native.cpp
  libraries/controllers/src/controllers/UserInputMapper.cpp
  tools/ac-client/src/ACClientApp.cpp
  tools/atp-client/src/ATPClientApp.cpp
  tools/ice-client/src/ICEClientApp.cpp
  tools/nitpick/src/TestCreator.cpp
  tools/skeleton-dump/src/SkeletonDumpApp.cpp
  tools/vhacd-util/src/VHACDUtilApp.cpp
Labels: CR Approved, enhancement, good first issue, rebuild

#943 Cmake: build in build dir
  CMakeLists.txt
  hifi_qt.py
  interface/CMakeLists.txt
  libraries/animation/CMakeLists.txt
  libraries/entities-renderer/CMakeLists.txt
  libraries/entities/CMakeLists.txt
  libraries/image/CMakeLists.txt
  libraries/render-utils/CMakeLists.txt
  libraries/shared/CMakeLists.txt
  tools/CMakeLists.txt
  tools/jsdoc/CMakeLists.txt
  tools/jsdoc/plugins/hifiJSONExport.js
  tools/nitpick/CMakeLists.txt
Labels: CMake, CR Approved, enhancement, needs QA (testing), rebuild

#1288 Add "Talk" link to "Help" menu.
  interface/src/Menu.cpp
  libraries/networking/src/NetworkingConstants.h
Labels: needs CR (code review), rebuild
