Repository vircadia/vircadia-native-core, pull requests merged in 2021-04, with the labels that each got.

#1069 Create App: Broken Url Report
  scripts/system/create/assets/images/processing.gif
  scripts/system/create/edit.js
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/modules/brokenURLReport.html
  scripts/system/create/modules/brokenURLReport.js
  scripts/system/html/css/edit-style.css
Labels: CR Approved, QA Approved, enhancement

#1132 Capture by value rather than by reference in RenderableModelEntityItem
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
Labels: CR Approved, bug, bugfix, needs QA (testing)

#1134 Add virtual destructor to TreeNodeBase
  libraries/script-engine/src/ScriptsModel.h
Labels: CR Approved, bugfix, needs QA (testing)

#1144 Convert line endings from CRLF to LF
  scripts/system/create/modules/brokenURLReport.html
Labels: bugfix

#1098 Add avatarEntities permissions
  assignment-client/src/avatars/AvatarMixerClientData.cpp
  assignment-client/src/avatars/AvatarMixerClientData.h
  assignment-client/src/avatars/AvatarMixerSlave.cpp
  assignment-client/src/avatars/ScriptableAvatar.cpp
  domain-server/resources/describe-settings.json
  domain-server/resources/web/wizard/js/wizard.js
  domain-server/src/DomainGatekeeper.cpp
  domain-server/src/DomainServerSettingsManager.cpp
  interface/resources/qml/hifi/AvatarApp.qml
  interface/src/Application.cpp
  interface/src/Application.h
  interface/src/ConnectionMonitor.cpp
  interface/src/avatar/AvatarManager.cpp
  interface/src/avatar/MyAvatar.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
  libraries/entities/src/EntityScriptingInterface.cpp
  libraries/entities/src/EntityScriptingInterface.h
  libraries/networking/src/AddressManager.cpp
  libraries/networking/src/AddressManager.h
  libraries/networking/src/DomainHandler.cpp
  libraries/networking/src/DomainHandler.h
  libraries/networking/src/LimitedNodeList.cpp
  libraries/networking/src/LimitedNodeList.h
  libraries/networking/src/Node.h
  libraries/networking/src/NodeList.cpp
  libraries/networking/src/NodeList.h
  libraries/networking/src/NodePermissions.cpp
  libraries/networking/src/NodePermissions.h
Labels: CR Approved, QA Approved, domain-server, enhancement, rebuild

#1124 Fix avatar parts rotating
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/render-utils/src/MeshPartPayload.h
Labels: CR Approved, QA Approved, bugfix

#1141 Fix ktx issue
  libraries/gpu/src/gpu/Texture_ktx.cpp
Labels: CR Approved, QA Approved, bugfix, renderer

#1127 Fix HIFI_MEMORY_DEBUGGING on Linux/gcc
  cmake/macros/MemoryDebugger.cmake
  libraries/audio/src/AudioHRTF.cpp
Labels: CR Approved, QA Approved, bug, bugfix, linux

#1143 Add missing override keywords.
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/networking/src/PacketReceiver.h
Labels: CR Approved, bugfix

#1145 Fix ShapeEntityItem::getRotateForPicking()
  libraries/entities/src/ShapeEntityItem.cpp
Labels: CR Approved, bugfix

#1147 Fix warning: NULL used in arithmetic
  domain-server/src/DomainServer.cpp
Labels: CR Approved, bugfix

#1148 Remove unused variable
  libraries/entities-renderer/src/RenderableGizmoEntityItem.cpp
Labels: CR Approved, bugfix

#1153 Log authentication events in the domain server
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServer.h
  libraries/embedded-webserver/src/HTTPConnection.h
Labels: CR Approved, QA Approved, domain-server, enhancement

#1155 Update Pal.qml for new Ban button
  interface/resources/qml/hifi/Pal.qml
Labels: CR Approved, QA Approved, bugfix

#1177 Update BUILD_WIN.md with Qt Info
  BUILD_WIN.md
Labels: docs

#1176 Update browser Chrome version
  libraries/networking/src/NetworkingConstants.h
Labels: CR Approved, QA Approved, housekeeping, rebuild

#1173 Fix mismatched if in CMake warning
  libraries/gpu-gl/CMakeLists.txt
Labels: CR Approved, rebuild

#1126 Hash Windows and Mac machine fingerprints.
  libraries/networking/src/FingerprintUtils.cpp
Labels: CR Approved, QA Approved, enhancement, osx, rebuild

#1163 Initial partial linux aarch64 support
  CMakeLists.txt
  cmake/externals/steamworks/CMakeLists.txt
  cmake/macros/SetupHifiLibrary.cmake
  cmake/ports/hifi-client-deps/CONTROL
  cmake/ports/nvtt/0001-Build-on-aarch64.patch
  cmake/ports/nvtt/0002-Hack-remove-include-sysctl.h-to-build-on-linux-a.patch
  cmake/ports/nvtt/portfile.cmake
  hifi_qt.py
  hifi_vcpkg.py
  plugins/CMakeLists.txt
Labels: CMake, CR Approved, QA Approved, linux

#1171 Implement VIRCADIA_MEMORY_DEBUGGING for Windows
  cmake/macros/MemoryDebugger.cmake
Labels: CR Approved, QA Approved, enhancement

#1178 Rename fbx to model serializers
  android/apps/interface/CMakeLists.txt
  android/apps/questInterface/CMakeLists.txt
  assignment-client/CMakeLists.txt
  interface/CMakeLists.txt
  libraries/animation/CMakeLists.txt
  libraries/avatars-renderer/CMakeLists.txt
  libraries/baking/CMakeLists.txt
  libraries/display-plugins/CMakeLists.txt
  libraries/entities-renderer/CMakeLists.txt
  libraries/entities/CMakeLists.txt
  libraries/graphics-scripting/CMakeLists.txt
  libraries/model-networking/CMakeLists.txt
  libraries/model-serializers/CMakeLists.txt
  libraries/model-serializers/src/FBX.h
  libraries/model-serializers/src/FBXSerializer.cpp
  libraries/model-serializers/src/FBXSerializer.h
  libraries/model-serializers/src/FBXSerializer_Material.cpp
  libraries/model-serializers/src/FBXSerializer_Mesh.cpp
  libraries/model-serializers/src/FBXSerializer_Node.cpp
  libraries/model-serializers/src/FBXToJSON.cpp
  libraries/model-serializers/src/FBXToJSON.h
  libraries/model-serializers/src/FBXWriter.cpp
  libraries/model-serializers/src/FBXWriter.h
  libraries/model-serializers/src/FST.cpp
  libraries/model-serializers/src/FST.h
  libraries/model-serializers/src/FSTReader.cpp
  libraries/model-serializers/src/FSTReader.h
  libraries/model-serializers/src/GLTFSerializer.cpp
  libraries/model-serializers/src/GLTFSerializer.h
  libraries/model-serializers/src/OBJSerializer.cpp
  libraries/model-serializers/src/OBJSerializer.h
  libraries/model-serializers/src/OBJWriter.cpp
  libraries/model-serializers/src/OBJWriter.h
  libraries/physics/CMakeLists.txt
  libraries/render-utils/CMakeLists.txt
  libraries/script-engine/CMakeLists.txt
  plugins/openvr/CMakeLists.txt
  tools/jsdoc/plugins/hifi.js
  tools/oven/CMakeLists.txt
  tools/skeleton-dump/CMakeLists.txt
  tools/vhacd-util/CMakeLists.txt
Labels: CR Approved, QA Approved, housekeeping

#938 Update to Qt 5.15.2
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  BUILD.md
  BUILD_OSX.md
  BUILD_WIN.md
  cmake/macros/ManuallyInstallOpenSSLForQt.cmake
  cmake/macros/SetupQt.cmake
  cmake/ports/openssl-windows/CONTROL
  cmake/ports/openssl-windows/ConfigureIncludeQuotesFix.patch
  cmake/ports/openssl-windows/EmbedSymbolsInStaticLibsZ7.patch
  cmake/ports/openssl-windows/STRINGIFYPatch.patch
  cmake/ports/openssl-windows/portfile.cmake
  hifi_qt.py
  libraries/networking/src/NetworkingConstants.h
  tools/qt-builder/README.md
  tools/qt-builder/patches/aec.patch
  tools/qt-builder/patches/mac-web-video.patch
  tools/qt-builder/patches/qfloat16.patch
  tools/qt-builder/patches/qtscript-crash-fix.patch
  tools/qt-builder/patches/win-qtwebengine.diff
  tools/qt-builder/qt5vars.bat
Labels: CR Approved, enhancement, merge right before snip, rebuild

#1181 Fix glTF mesh colors
  libraries/model-serializers/src/GLTFSerializer.cpp
Labels: CR Approved, QA Approved, bugfix, renderer

#1161 Fix settings (QML) spin box stepping
  interface/resources/qml/controlsUit/SpinBox.qml
  interface/resources/qml/dialogs/preferences/SpinBoxPreference.qml
  interface/resources/qml/dialogs/preferences/SpinnerSliderPreference.qml
  interface/src/ui/PreferencesDialog.cpp
  libraries/shared/src/Preferences.h
Labels: CR Approved, QA Approved, bugfix

#1193 Update Snapshot.cpp
  interface/src/ui/Snapshot.cpp
Labels: CR Approved, QA Approved, allow-build-upload, hifi migration, rebuild

#1188 Link to pthread last
  tools/nitpick/CMakeLists.txt
Labels: CR Approved, QA Approved, linux

#692 The domain server should see Packet ID=1 as a (broken) attempt to connect to the domain server
  domain-server/src/DomainServer.cpp
  libraries/networking/src/udt/PacketHeaders.cpp
  libraries/networking/src/udt/PacketHeaders.h
  tools/dissectors/1-hfudt.lua
Labels: CR Approved, QA Approved, allow-build-upload, enhancement, rebuild
