Repository vircadia/vircadia-native-core, pull requests merged in 2021-06, with the labels that each got.

#1236 Some APIDocs metadata fixes.
  tools/jsdoc/config.json
  tools/jsdoc/hifi-jsdoc-template/publish.js
  tools/jsdoc/hifi-jsdoc-template/static/CNAME
  tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl
  tools/jsdoc/package.json
  tools/jsdoc/root.js
Labels: CR Approved, bugfix, docs

#1239 Conditionally include WebRTCSignalingServer.h
  domain-server/src/DomainServer.h
Labels: CR Approved, web app sdk

#1207 Fix draco compilation on gcc11
  cmake/ports/draco/portfile.cmake
Labels: CMake, CR Approved, bugfix, confirmed, linux, rebuild

#1227 Update MacOS packaging instructions.
  INSTALLER.md
Labels: CR Approved, docs

#1206 drop remaining references to QScriptEngineDebugger
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngines.cpp
Labels: CR Approved, QA Approved, allow-build-upload, rebuild, scripting api change

#1245 Add basic MSIX instructions to INSTALLER.md.
  INSTALLER.md
Labels: docs

#1254 Fix typo in WebSocket~onMessageCallback API documention.
  libraries/script-engine/src/WebSocketClass.cpp
Labels: CR Approved, bugfix, docs

#1258 Update WebRTC Windows package
  cmake/ports/webrtc/CONTROL
  cmake/ports/webrtc/README.md
  cmake/ports/webrtc/copy-VCPKG-file-win.cmd
  cmake/ports/webrtc/portfile.cmake
  libraries/audio-client/src/AudioClient.cpp
  libraries/audio-client/src/AudioClient.h
  libraries/shared/src/shared/WebRTC.h
Labels: CR Approved, QA Approved, enhancement

#1252 Make Zone Selector for "renderWithZones" in "Create" app HMD Compliant.
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/html/css/edit-style.css
Labels: CR Approved, QA Approved, enhancement

#936 Improve Qt handling in CMake
  BUILD_LINUX.md
  CMakeLists.txt
  cmake/macros/SetupQt.cmake
  cmake/ports/quazip/portfile.cmake
  hifi_qt.py
  hifi_utils.py
  hifi_vcpkg.py
  interface/CMakeLists.txt
  prebuild.py
  tools/nitpick/CMakeLists.txt
Labels: CMake, CR Approved, enhancement, needs QA (testing), rebuild

#1249 Update user docs links "docs.vircadia.dev" -> "docs.vircadia.com".
  domain-server/resources/web/wizard/index.shtml
  interface/resources/html/tabletHelp.html
  interface/resources/qml/hifi/avatarPackager/AvatarPackagerApp.qml
  interface/resources/qml/hifi/avatarPackager/AvatarProject.qml
  interface/resources/qml/hifi/avatarapp/MessageBoxes.qml
  interface/resources/qml/hifi/commerce/checkout/Checkout.qml
  interface/resources/qml/hifi/commerce/purchases/Purchases.qml
  interface/resources/qml/hifi/commerce/wallet/Help.qml
  interface/src/Application.cpp
  interface/src/avatar/AvatarDoctor.cpp
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars-renderer/src/avatars-renderer/ScriptAvatar.h
  libraries/avatars/src/AvatarData.h
  libraries/avatars/src/ScriptAvatarData.h
  libraries/image/src/image/TextureProcessing.h
  libraries/midi/src/Midi.h
  libraries/script-engine/src/ScriptEngine.h
  server-console/src/content-update.html
  server-console/src/splash.html
  tools/jsdoc/api-mainpage.md
Labels: CR Approved, bugfix, docs

#1261 Update webapp feature branch with current master
  .github/workflows/pr_build.yml
  .grenrc.js
  BUILD_LINUX.md
  CMakeLists.txt
  INSTALLER.md
  README.md
  cmake/macros/SetupQt.cmake
  cmake/ports/draco/portfile.cmake
  cmake/ports/quazip/portfile.cmake
  hifi_qt.py
  hifi_utils.py
  hifi_vcpkg.py
  interface/CMakeLists.txt
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngines.cpp
  libraries/script-engine/src/WebSocketClass.cpp
  prebuild.py
  screenshare/package-lock.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/html/css/edit-style.css
  tools/doxygen/README.md
  tools/jsdoc/config.json
  tools/jsdoc/hifi-jsdoc-template/publish.js
  tools/jsdoc/hifi-jsdoc-template/static/CNAME
  tools/jsdoc/hifi-jsdoc-template/tmpl/layout.tmpl
  tools/jsdoc/package.json
  tools/jsdoc/root.js
  tools/nitpick/CMakeLists.txt
  tools/qt-builder/patches/qt5.15-gcc11.patch
Labels: web app

#1223 Ensuring minimal documentation for classes declared in script-engine
  libraries/script-engine/src/AbstractScriptingServicesInterface.h
  libraries/script-engine/src/ArrayBufferClass.h
  libraries/script-engine/src/ArrayBufferPrototype.h
  libraries/script-engine/src/ArrayBufferViewClass.h
  libraries/script-engine/src/AssetScriptingInterface.h
  libraries/script-engine/src/AudioScriptingInterface.h
  libraries/script-engine/src/BatchLoader.h
  libraries/script-engine/src/ConsoleScriptingInterface.h
  libraries/script-engine/src/DataViewClass.h
  libraries/script-engine/src/DataViewPrototype.h
  libraries/script-engine/src/EventTypes.h
  libraries/script-engine/src/FileScriptingInterface.h
  libraries/script-engine/src/KeyEvent.h
  libraries/script-engine/src/MIDIEvent.h
  libraries/script-engine/src/Mat4.h
  libraries/script-engine/src/MenuItemProperties.h
  libraries/script-engine/src/ModelScriptingInterface.h
  libraries/script-engine/src/MouseEvent.h
  libraries/script-engine/src/Quat.h
  libraries/script-engine/src/RecordingScriptingInterface.h
  libraries/script-engine/src/SceneScriptingInterface.h
  libraries/script-engine/src/ScriptAudioInjector.h
  libraries/script-engine/src/ScriptCache.h
  libraries/script-engine/src/ScriptEngine.h
  libraries/script-engine/src/ScriptEngineLogging.h
  libraries/script-engine/src/ScriptEngines.h
  libraries/script-engine/src/ScriptGatekeeper.h
  libraries/script-engine/src/ScriptUUID.h
  libraries/script-engine/src/ScriptsModel.h
  libraries/script-engine/src/ScriptsModelFilter.h
  libraries/script-engine/src/SpatialEvent.h
  libraries/script-engine/src/StackTestScriptingInterface.h
  libraries/script-engine/src/TouchEvent.h
  libraries/script-engine/src/TypedArrayPrototype.h
  libraries/script-engine/src/TypedArrays.h
  libraries/script-engine/src/UsersScriptingInterface.h
  libraries/script-engine/src/Vec3.h
  libraries/script-engine/src/WebSocketClass.h
  libraries/script-engine/src/WebSocketServerClass.h
  libraries/script-engine/src/WheelEvent.h
  libraries/script-engine/src/XMLHttpRequestClass.h
Labels: CR Approved, allow-build-upload, docs, enhancement
