Repository vircadia/vircadia-native-core, pull requests merged in 2021-02, with the labels that each got.

#987 Update build docs slightly.
  BUILD.md
  BUILD_WIN.md
  INSTALLER.md
Labels: docs

#971 Fix crashes when running with QML disabled in VR
  interface/src/AboutUtil.cpp
  interface/src/Bookmarks.cpp
  interface/src/avatar/AvatarPackager.cpp
  interface/src/scripting/AssetMappingsScriptingInterface.cpp
  interface/src/scripting/DesktopScriptingInterface.cpp
  interface/src/scripting/HMDScriptingInterface.cpp
  interface/src/scripting/WindowScriptingInterface.cpp
  interface/src/ui/ApplicationOverlay.cpp
  interface/src/ui/InteractiveWindow.cpp
  interface/src/ui/overlays/Overlays.cpp
  interface/src/ui/overlays/QmlOverlay.cpp
  libraries/ui/src/DockWidget.cpp
  libraries/ui/src/InfoView.cpp
  libraries/ui/src/OffscreenQmlElement.h
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/QmlFragmentClass.cpp
  libraries/ui/src/QmlWebWindowClass.cpp
  libraries/ui/src/QmlWindowClass.cpp
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  plugins/openvr/src/OpenVrHelpers.cpp
Labels: CR Approved, QA Approved, Severity: Low, VR, bugfix, rebuild

#932 Create Application: Snap To Next Clicked Surface
  interface/resources/fonts/vircadia_glyphs.ttf
  scripts/system/controllers/controllerModules/inEditMode.js
  scripts/system/create/audioFeedback/audioFeedback.js
  scripts/system/create/audioFeedback/sounds/action.mp3
  scripts/system/create/edit.js
  scripts/system/create/entityList/entityList.js
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/entitySelectionTool/entitySelectionTool.js
  scripts/system/html/css/edit-style.css
Labels: CR Approved, QA Approved, enhancement

#996 Update About Dialog and remove Vircadia "Alpha" references
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  LICENSE
  android/build_android.sh
  cmake/installer/installer-header.bmp
  cmake/installer/uninstaller-header.bmp
  cmake/macros/GenerateInstallers.cmake
  interface/resources/qml/hifi/dialogs/TabletAboutDialog.qml
  interface/src/AboutUtil.cpp
  interface/src/AboutUtil.h
Labels: CR Approved, QA Approved, enhancement, scripting api change

#1009 Various Domain Server Wizard Fixes
  domain-server/resources/web/js/shared.js
  domain-server/resources/web/wizard/js/wizard.js
Labels: CR Approved, QA Approved, bugfix, domain-server, enhancement

#951 Model Entities: useOriginalPivot Property
  interface/src/ui/Stats.h
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderableModelEntityItem.h
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/hfm/src/hfm/HFM.cpp
  libraries/networking/src/udt/PacketHeaders.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/Model.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/edit.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/qml/NewModelDialog.qml
Labels: CR Approved, docs, enhancement, merge right before snip, needs QA (testing), packet version change, question, rebuild, renderer, scripting api change

#988 Feature/web entity user agent
  interface/resources/qml/Web3DSurface.qml
  interface/resources/qml/controls/+webengine/FlickableWebViewCore.qml
  interface/resources/qml/controls/FlickableWebViewCore.qml
  interface/resources/qml/controls/WebView.qml
  libraries/entities-renderer/src/RenderableWebEntityItem.cpp
  libraries/entities-renderer/src/RenderableWebEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/WebEntityItem.cpp
  libraries/entities/src/WebEntityItem.h
  libraries/networking/src/NetworkingConstants.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/ui/src/ui/types/RequestFilters.cpp
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: CR Approved, QA Approved, enhancement, merge right before snip, packet version change, scripting api change

#1017 Fix profile errors in QML. (also add FIXME's)
  interface/resources/qml/controls/+webengine/FlickableWebViewCore.qml
  interface/resources/qml/controls/FlickableWebViewCore.qml
  interface/resources/qml/controls/TabletWebScreen.qml
  interface/resources/qml/controls/TabletWebView.qml
  interface/resources/qml/controls/WebView.qml
Labels: CR Approved, QA Approved, bugfix

#1029 Fix for offset soft attachments
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/render-utils/src/Model.cpp
Labels: CR Approved, QA Approved, bugfix, rebuild, renderer

#1020 Text Entity alignment property
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.h
  libraries/render-utils/src/TextRenderer3D.cpp
  libraries/render-utils/src/TextRenderer3D.h
  libraries/render-utils/src/text/Font.cpp
  libraries/render-utils/src/text/Font.h
  libraries/shared/src/TextAlignment.cpp
  libraries/shared/src/TextAlignment.h
  libraries/shared/src/TextEffect.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityProperties/html/js/entityProperties.js
Labels: CR Approved, QA Approved, bugfix, docs, enhancement, merge right before snip, packet version change, renderer, scripting api change

#1030 Create App FEB2021 bundle
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/html/css/edit-style.css
Labels: CR Approved, QA Approved, enhancement

#1041 Fix rotation of billboarded entities with parents
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/GizmoEntityItem.cpp
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/entities/src/PolyVoxEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/render-utils/src/Model.cpp
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
Labels: CR Approved, bugfix, docs, needs QA (testing), rebuild, renderer, scripting api change

#1040 Name a bunch of threads
  .gitignore
  assignment-client/src/AssignmentClient.cpp
  assignment-client/src/audio/AudioMixerSlavePool.cpp
  assignment-client/src/octree/OctreeServer.cpp
  domain-server/src/DomainServer.cpp
  interface/src/Application.cpp
  libraries/audio/src/AudioInjectorManager.cpp
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
  libraries/gpu-gl-common/src/gpu/gl/GLTextureTransfer.cpp
  libraries/networking/src/ResourceManager.cpp
  libraries/networking/src/udt/SendQueue.cpp
  libraries/qml/src/qml/impl/SharedObject.cpp
  libraries/script-engine/src/ScriptEngine.cpp
  libraries/shared/src/GenericThread.cpp
  libraries/shared/src/SettingInterface.cpp
  libraries/shared/src/ThreadHelpers.h
  libraries/ui/src/ui/TabletScriptingInterface.cpp
  plugins/openvr/src/OpenVrDisplayPlugin.cpp
  plugins/openvr/src/ViveControllerManager.cpp
Labels: CR Approved, audio-mixer, needs QA (testing), renderer, settings, threading/deadlock (beware)

#800 Updated build instructions for Oculus Quest
  BUILD_ANDROID.md
Labels: docs

#1034 merge V2021.1.0 rc into master
  libraries/avatars-renderer/src/avatars-renderer/SkeletonModel.cpp
  libraries/entities-renderer/src/RenderableEntityItem.cpp
  libraries/entities-renderer/src/RenderableEntityItem.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.cpp
  libraries/entities-renderer/src/RenderablePolyLineEntityItem.h
  libraries/entities-renderer/src/RenderablePolyVoxEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.cpp
  libraries/entities-renderer/src/RenderableShapeEntityItem.h
  libraries/entities-renderer/src/RenderableTextEntityItem.cpp
  libraries/entities-renderer/src/RenderableTextEntityItem.h
  libraries/entities/src/EntityItem.cpp
  libraries/entities/src/EntityItem.h
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/EntityItemProperties.h
  libraries/entities/src/EntityPropertyFlags.h
  libraries/entities/src/EntityTreeElement.cpp
  libraries/entities/src/GizmoEntityItem.cpp
  libraries/entities/src/ModelEntityItem.cpp
  libraries/entities/src/ModelEntityItem.h
  libraries/entities/src/PolyVoxEntityItem.cpp
  libraries/entities/src/ShapeEntityItem.cpp
  libraries/entities/src/TextEntityItem.cpp
  libraries/entities/src/TextEntityItem.h
  libraries/networking/src/udt/PacketHeaders.h
  libraries/octree/src/OctreePacketData.h
  libraries/render-utils/src/Model.cpp
  libraries/render-utils/src/TextRenderer3D.cpp
  libraries/render-utils/src/TextRenderer3D.h
  libraries/render-utils/src/text/Font.cpp
  libraries/render-utils/src/text/Font.h
  libraries/shared/src/SpatiallyNestable.cpp
  libraries/shared/src/SpatiallyNestable.h
  libraries/shared/src/TextAlignment.cpp
  libraries/shared/src/TextAlignment.h
  libraries/shared/src/TextEffect.h
  scripts/system/create/assets/data/createAppTooltips.json
  scripts/system/create/entityList/html/entityList.html
  scripts/system/create/entityList/html/js/entityList.js
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/html/css/edit-style.css
Labels: housekeeping

#968 MacOS Qt 5.15.2
  BUILD.md
  BUILD_OSX.md
  hifi_qt.py
  tools/qt-builder/README.md
Labels: CR Approved, allow-build-upload, enhancement, needs QA (testing), rebuild

#1063 Fix tooltips
  scripts/system/create/assets/data/createAppTooltips.json
Labels: CR Approved, QA Approved, bugfix

#1057 Add release name to end of installers.
  cmake/macros/GenerateInstallers.cmake
Labels: CR Approved, QA Approved, bugfix

#1055 Update pkg-scripts.
  pkg-scripts/README
  pkg-scripts/README.md
  pkg-scripts/make-deb-server
  pkg-scripts/make-rpm-server
Labels: QA Approved, docs, enhancement, housekeeping

#1014 Add "RELEASE_NAME" to BUILD.md
  BUILD.md
Labels: CR Approved, docs

#999 Add onboarding configuration wizard to tutorial serverless
  interface/resources/qml/hifi/avatarapp/MessageBoxes.qml
  interface/resources/serverless/tutorial.json
  scripts/defaultScripts.js
  scripts/system/away.js
  scripts/system/onEscape.js
  scripts/system/onFirstRun.js
Labels: CR Approved, QA Approved, enhancement
