Repository vircadia/vircadia-native-core, pull requests merged in 2022-06, with the labels that each got.

#1661 More app: New UI 2022.
  scripts/system/more/app-more.js
  scripts/system/more/blank_minus-16.png
  scripts/system/more/blank_plus-16.png
  scripts/system/more/css/FiraSans-Regular.ttf
  scripts/system/more/css/FiraSans-SemiBold.ttf
  scripts/system/more/css/FiraSans.license
  scripts/system/more/css/sidewalk.png
  scripts/system/more/css/styles.css
  scripts/system/more/del-x-16.png
  scripts/system/more/minus-16.png
  scripts/system/more/more.html
  scripts/system/more/plus-16.png
  scripts/system/more/search-32.png
Labels: CR Approved, QA Approved

#1663 Fix ScriptAvatar.scale doc.
  libraries/avatars-renderer/src/avatars-renderer/ScriptAvatar.h
Labels: docs

#1670 Fix Avatar targetScaleChanged JSDoc.
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
Labels: CR Approved, bugfix
