Repository vircadia/vircadia-native-core, pull requests merged in 2022-10, with the labels that each got.

#1699 Handle skeleton joints from other clients having different order.
  interface/src/avatar/OtherAvatar.cpp
  libraries/animation/src/Rig.cpp
  libraries/animation/src/Rig.h
  libraries/avatars-renderer/src/avatars-renderer/Avatar.cpp
  libraries/avatars-renderer/src/avatars-renderer/Avatar.h
  libraries/avatars/src/AvatarData.cpp
  libraries/avatars/src/AvatarData.h
Labels: CR Approved, bugfix

#1705 Re-enabled ICE server packaging in ubuntu server deb scripts.
  pkg-scripts/README.md
  pkg-scripts/make-deb-server
  pkg-scripts/server-postinst
  pkg-scripts/server-prerm
  pkg-scripts/server-rules
  pkg-scripts/vircadia-ice-server@.service
  pkg-scripts/vircadia-server.spec
  pkg-scripts/vircadia-server.target
  pkg-scripts/vircadia-server@.target
Labels: enhancement

#1704 Fixed Metaverse places request in explore app.
  scripts/communityScripts/explore/explore.html
Labels: bugfix
