Repository vircadia/vircadia-native-core, pull requests merged in 2022-02, with the labels that each got.

#1587 Safer linux distro version checks in Qt installation script.
  hifi_qt.py
Labels: CR Approved, QA Approved, allow-build-upload, linux

#1589 Fix dedicated IPFS gateway rejecting download requests.
  hifi_utils.py
Labels: CR Approved, QA Approved, bugfix

#1586 Add UI for setting metaverse server URL.
  interface/resources/images/lock.svg
  interface/resources/images/unlock.svg
  interface/resources/qml/LoginDialog/LinkAccountBody.qml
  interface/resources/qml/LoginDialog/SignUpBody.qml
  interface/resources/qml/controlsUit/TextField.qml
  interface/src/Application.cpp
  interface/src/scripting/AccountServicesScriptingInterface.cpp
  interface/src/scripting/AccountServicesScriptingInterface.h
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/AccountManager.h
  libraries/networking/src/MetaverseAPI.cpp
  libraries/networking/src/MetaverseAPI.h
Labels: enhancement, CR Approved, QA Approved, allow-build-upload

#1597 Update API documentation for Window.prompt().
  interface/src/scripting/WindowScriptingInterface.h
Labels: docs, CR Approved

#1592 Add Arch Linux build guide.
  BUILD_LINUX.md
Labels: docs, CR Approved

#1595 Disabled "Visit in VR" button in Domain server web panel.
  domain-server/resources/web/settings/js/settings.js
Labels: QA Approved, domain-server, bugfix

#1606 Enabled vcpkg bootstrapping in PR and master builds.
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: rebuild

#1602 Fixed python prebuild script getting stuck trying to lock a file without permission.
  hifi_singleton.py
  prebuild.py
Labels: CR Approved, QA Approved, CMake

#1603 Domain server first time wizard improvements and fixes.
  domain-server/resources/web/web-new/dist/spa/css/183.6a262c69.css
  domain-server/resources/web/web-new/dist/spa/css/885.684a1d9d.css
  domain-server/resources/web/web-new/dist/spa/css/app.31d6cfe0.css
  domain-server/resources/web/web-new/dist/spa/css/app.fc06f7aa.css
  domain-server/resources/web/web-new/dist/spa/index.html
  domain-server/resources/web/web-new/dist/spa/js/183.74af68ff.js
  domain-server/resources/web/web-new/dist/spa/js/197.1d65bbb2.js
  domain-server/resources/web/web-new/dist/spa/js/264.9e82b317.js
  domain-server/resources/web/web-new/dist/spa/js/870.5e46cfb2.js
  domain-server/resources/web/web-new/dist/spa/js/885.c283608c.js
  domain-server/resources/web/web-new/dist/spa/js/961.c50bc468.js
  domain-server/resources/web/web-new/dist/spa/js/app.d7a0143e.js
  domain-server/resources/web/web-new/dist/spa/js/app.eeccaf1c.js
  domain-server/resources/web/web-new/dist/spa/js/vendor.8c115444.js
  domain-server/resources/web/web-new/dist/spa/js/vendor.f7426f3d.js
  domain-server/resources/web/web-new/package-lock.json
  domain-server/resources/web/web-new/package.json
  domain-server/resources/web/web-new/src/css/app.scss
  domain-server/resources/web/web-new/src/layouts/FirstTimeWizard.vue
  domain-server/resources/web/web-new/src/pages/FirstTimeWizard/Index.vue
Labels: rebuild, CR Approved, QA Approved, domain-server

#1298 Remove snaps in goto & nearby teleport references
  interface/resources/qml/hifi/Pal.qml
Labels: rebuild, CR Approved, QA Approved, bugfix

#1593 Added hash checks for downloaded items in python build scripts.
  hifi_qt.py
  hifi_utils.py
  hifi_vcpkg.py
  prebuild.py
Labels: enhancement, CR Approved, CMake
