Repository vircadia/vircadia-native-core, pull requests merged in 2022-01, with the labels that each got.

#1560 Resolve #1557 where Windows builds fail on GHA due to incompatible NSIS version.
  .github/workflows/pr_build.yml
Labels: CR Approved, QA Approved, allow-build-upload, bugfix

#1562 Mirror NSIS fix for PR builds to master builds on GHA.
  .github/workflows/master_build.yml
Labels: rebuild, CR Approved, allow-build-upload, bugfix

#1567 Fix MultiHash issues added in PR #1468.
  interface/src/ModelPackager.cpp
  libraries/model-serializers/src/FST.cpp
  libraries/model-serializers/src/FSTReader.cpp
  libraries/model-serializers/src/FSTReader.h
Labels: CR Approved, QA Approved, bugfix

#1485 Housekeeping: Explicitly encode QStrings to utf8.
  interface/src/Util.cpp
  interface/src/commerce/Wallet.cpp
  libraries/networking/src/AccountManager.cpp
  libraries/networking/src/DomainAccountManager.cpp
  libraries/networking/src/UserActivityLogger.cpp
  libraries/octree/src/OctreeDataUtils.cpp
Labels: housekeeping, CR Approved, QA Approved

#1572 Fixed some Linux distros being deemed unconditionally too old to use Qt.
  hifi_qt.py
Labels: CR Approved, bugfix, linux, CMake

#1502 Remove deprecated usage of setUserData.
  libraries/ui/src/OffscreenUi.cpp
  libraries/ui/src/OffscreenUi.h
  libraries/ui/src/VrMenu.cpp
  libraries/ui/src/VrMenu.h
Labels: enhancement, housekeeping, CR Approved, QA Approved

#1505 Documentation format revisions.
  BUILD_LINUX.md
  BUILD_OSX.md
  README.md
Labels: docs, CR Approved

#1575 Replace call to devicePixelRatio() with devicePixelRatioF().
  libraries/display-plugins/src/display-plugins/OpenGLDisplayPlugin.cpp
Labels: renderer, CR Approved, QA Approved, allow-build-upload, bugfix

#1579 Update Unity Avatar Exporter with fixed cross-platform support.
  tools/unity-avatar-exporter/Assets/Editor/AvatarExporter/AvatarExporter.cs
  tools/unity-avatar-exporter/Assets/README.txt
  tools/unity-avatar-exporter/avatarExporter.unitypackage
Labels: CR Approved, QA Approved, bugfix

#1574 Add option to render green boxes for missing models.
  interface/src/Menu.cpp
  interface/src/Menu.h
  libraries/entities-renderer/src/EntityTreeRenderer.cpp
  libraries/entities-renderer/src/EntityTreeRenderer.h
  libraries/entities-renderer/src/RenderableModelEntityItem.cpp
  libraries/script-engine/src/SceneScriptingInterface.cpp
  libraries/script-engine/src/SceneScriptingInterface.h
Labels: enhancement, scripting api change, renderer, CR Approved, QA Approved

#1573 Make build system more robust and add IPFS gateway support.
  CMakeLists.txt
  cmake/ExternalAssetsConfig.cmake
  cmake/externals/GifCreator/CMakeLists.txt
  cmake/externals/LibOVR/CMakeLists.txt
  cmake/externals/LibOVRPlatform/CMakeLists.txt
  cmake/externals/crashpad/CMakeLists.txt
  cmake/externals/hifiAudioCodec/CMakeLists.txt
  cmake/externals/neuron/CMakeLists.txt
  cmake/externals/sixense/CMakeLists.txt
  cmake/externals/steamworks/CMakeLists.txt
  cmake/externals/tbb/CMakeLists.txt
  cmake/externals/wasapi/CMakeLists.txt
  cmake/macros/ExternalAssetsUtils.cmake
  cmake/ports/aristo/portfile.cmake
  cmake/ports/glad/portfile.cmake
  cmake/ports/openssl-android/portfile.cmake
  cmake/ports/polyvox/portfile.cmake
  cmake/ports/quazip/portfile.cmake
  cmake/ports/sranipal/portfile.cmake
  cmake/ports/vhacd/portfile.cmake
  cmake/ports/webrtc/portfile.cmake
  hifi_qt.py
  hifi_utils.py
  hifi_vcpkg.py
  launchers/qt/CMakeLists.txt
  prebuild.py
Labels: enhancement, rebuild, CR Approved, QA Approved, allow-build-upload, CMake

#1580 Improve Metaverse sign-up UX.
  interface/resources/qml/LoginDialog/SignUpBody.qml
  interface/src/ui/LoginDialog.cpp
  interface/src/ui/LoginDialog.h
Labels: rebuild, CR Approved, QA Approved, allow-build-upload

#1576 Fix sdl2 linking errors when built against new Wayland.
  cmake/ports/sdl2/fix-build-against-wayland-1_20.patch
  cmake/ports/sdl2/portfile.cmake
Labels: rebuild, CR Approved, allow-build-upload, bugfix, linux, CMake

#1588 Update image branding from High Fidelity to Vircadia.
  interface/resources/images/AvatarTheftBanner.png
  interface/resources/images/steam-min-spec-failed.png
Labels: allow-build-upload, hifi migration
