Repository vircadia/vircadia-native-core, pull requests merged in 2022-08, with the labels that each got.

#1677 Finalizing external build asset migration to IPFS.
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  cmake/ExternalAssetsConfig.cmake
  cmake/macros/ExternalAssetsUtils.cmake
  cmake/ports/nlohmann-json/portfile.cmake
  cmake/ports/openssl-unix/portfile.cmake
  cmake/ports/openssl-windows/portfile.cmake
  cmake/ports/zlib/portfile.cmake
  hifi_android.py
  hifi_vcpkg.py
  tools/qt-builder/README.md
Labels: CR Approved, CMake, android

#1678 Enable vcpkg bootstrapping by default.
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  BUILD_WIN.md
  cmake/macros/TargetBullet.cmake
  cmake/ports/bullet3/CONTROL
  cmake/ports/bullet3/bullet-git-fix-build-clang-8.patch
  cmake/ports/bullet3/cmake-fix.patch
  cmake/ports/bullet3/enable-profiling.patch
  cmake/ports/bullet3/portfile.cmake
  cmake/ports/bullet3/usage
  cmake/ports/bullet3/vcpkg.json
  cmake/ports/opus/CONTROL
  cmake/ports/opus/portfile.cmake
  cmake/ports/opus/vcpkg.json
  cmake/ports/vcpkg-cmake-config/copyright
  cmake/ports/vcpkg-cmake-config/portfile.cmake
  cmake/ports/vcpkg-cmake-config/vcpkg-port-config.cmake
  cmake/ports/vcpkg-cmake-config/vcpkg.json
  cmake/ports/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake
  cmake/ports/vcpkg-cmake/portfile.cmake
  cmake/ports/vcpkg-cmake/vcpkg-port-config.cmake
  cmake/ports/vcpkg-cmake/vcpkg.json
  cmake/ports/vcpkg-cmake/vcpkg_cmake_build.cmake
  cmake/ports/vcpkg-cmake/vcpkg_cmake_configure.cmake
  cmake/ports/vcpkg-cmake/vcpkg_cmake_install.cmake
  hifi_vcpkg.py
Labels: rebuild, CR Approved, CMake

#1686 Updated build docs to mention git submodules.
  BUILD_LINUX.md
  BUILD_WIN.md
Labels: docs

#1687 Improve Material entity documentation.
  libraries/entities/src/EntityItemProperties.cpp
  libraries/procedural/src/procedural/ProceduralMaterialCache.cpp
Labels: docs

#1688 Improve package download error logging in python build scripts.
  hifi_utils.py
Labels: enhancement, CMake

#1689 Fix Zone entity avatar priority default initialization.
  libraries/entities/src/ZoneEntityItem.h
Labels: housekeeping, CR Approved

#1690 Fix some entity scripting API docs.
  libraries/entities/src/EntityItemProperties.cpp
  libraries/entities/src/HazePropertyGroup.h
Labels: docs

#1691 Use GHA build artifacts instead of custom uploader.
  .github/workflows/pr_build.yml
Labels: CR Approved

#1692 Use GHA artifacts instead of custom uploader in master builds.
  .github/workflows/master_build.yml
Labels: enhancement, CR Approved

#1694 Remove self-hosted GitHub Actions Runner and Runner dependent code.
  .github/workflows/pr_build.yml
Labels: housekeeping

#1693 Updated .deb package creation script to assume normal build configuration.
  pkg-scripts/README.md
  pkg-scripts/make-deb-server
  pkg-scripts/server-postinst
  pkg-scripts/vircadia-assignment-client.service
  pkg-scripts/vircadia-assignment-client@.service
  pkg-scripts/vircadia-domain-server.service
  pkg-scripts/vircadia-domain-server@.service
Labels: enhancement
