Repository vircadia/vircadia-native-core, pull requests merged in 2022-03, with the labels that each got.

#1616 Downgraded GHA Windows environment to Server 2019.
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
Labels: CR Approved, QA Approved

#1607 Create skeleton of the native client library and Unity SDK.
  .github/workflows/master_build.yml
  .github/workflows/pr_build.yml
  CMakeLists.txt
  cmake/macros/ThreadDebugger.cmake
  cmake/ports/catch2/CONTROL
  cmake/ports/catch2/fix-install-path.patch
  cmake/ports/catch2/portfile.cmake
  cmake/ports/hifi-deps/CONTROL
  interface/CMakeLists.txt
  libraries/vircadia-client/CMakeLists.txt
  libraries/vircadia-client/README.md
  libraries/vircadia-client/src/common.h
  libraries/vircadia-client/src/version.cpp
  libraries/vircadia-client/src/version.h
  libraries/vircadia-client/tests/CMakeLists.txt
  libraries/vircadia-client/tests/version.cpp
Labels: CR Approved, CMake

#1625 Updated Arch Linux Build Doc to Recorder Directory Command.
  BUILD_LINUX.md
Labels: docs, CR Approved

#1629 Document packet header formats
  libraries/networking/src/NLPacket.h
  libraries/networking/src/udt/ControlPacket.h
  libraries/networking/src/udt/Packet.h
Labels: docs
