Repository vircadia/vircadia-native-core, pull requests merged in 2022-11, with the labels that each got.

#1707 Clarify Users scripting API doc.
  libraries/script-engine/src/UsersScriptingInterface.h
Labels: docs

#1722 Update BUILD_LINUX.md
  BUILD_LINUX.md
Labels: docs

#1716 Added capabilities object to domain server -> metaverse heartbeat requests.
  domain-server/src/DomainServer.cpp
  domain-server/src/DomainServerExporter.h
Labels: enhancement, CR Approved

#1712 CVE-2007-4559 Patch
  hifi_utils.py
Labels: CR Approved, allow-build-upload, bugfix

#1725 Add Ubuntu 20.04 Server build instructions.
  BUILD_LINUX.md
Labels: docs
