Repository vircadia/vircadia-native-core, pull requests merged in 2022-05, with the labels that each got.

#1647 Clarify skeleton model URL file types.
  assignment-client/src/avatars/ScriptableAvatar.h
  interface/src/avatar/MyAvatar.h
  libraries/avatars-renderer/src/avatars-renderer/ScriptAvatar.h
  libraries/avatars/src/AvatarData.h
Labels: docs, CR Approved

#1654 Instructions for building native client library for Android.
  libraries/vircadia-client/BUILD_ANDROID.md
  libraries/vircadia-client/README.md
  libraries/vircadia-client/android/openssl_configure_android.sh
  libraries/vircadia-client/android/openssl_fix_includes.diff
  libraries/vircadia-client/android/qt_configure_android.sh
  libraries/vircadia-client/android/tbb_configure_android.sh
  libraries/vircadia-client/android/tbb_configure_android64.sh
  libraries/vircadia-client/android/tbb_remove_emit.patch
  libraries/vircadia-client/android/wreckage.patch
Labels: docs

#1658 Create app: Added Material Data Assistant.
  scripts/system/create/entityProperties/html/entityProperties.html
  scripts/system/create/entityProperties/html/js/entityProperties.js
  scripts/system/create/entityProperties/html/js/materialAssistant.js
  scripts/system/html/css/img/sidewalk.png
  scripts/system/html/css/materialAssistant.css
Labels: CR Approved, QA Approved, allow-build-upload

#1657 Added new avatars to default avatar bookmarks.
  interface/resources/avatar/bookmarks/avatarbookmarks.json
Labels: enhancement, rebuild, QA Approved, allow-build-upload
